import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

const seedPath = path.join(rootDir, 'data/seed.json');
const seed = JSON.parse(fs.readFileSync(seedPath, 'utf-8'));

// 37개 신규 아이템 ID 목록
const newIds = new Set([
  'cvs-nongshim-neoguri-bowl-111',
  'cvs-ottogi-chamkkae-ramen-cup-110',
  'cvs-ottogi-yeol-ramen-cup-105',
  'cvs-paldo-wangttukkeong-110',
  'cvs-gs25-omori-kimchi-stew-cup-160',
  'cvs-samyang-cheese-buldak-cup-105',
  'cvs-nongshim-ansungtangmyun-cup-66',
  'cvs-gs25-idol-popular-sandwich-150',
  'cvs-gs25-double-bulgogi-burger-190',
  'cvs-cu-taiwan-condensed-milk-sandwich-130',
  'cvs-cu-spicy-chicken-burger-180',
  'cvs-seven-bulgogi-burger-175',
  'cvs-seven-egg-potato-sandwich-160',
  'cvs-lotte-uiseong-garlic-frank-70',
  'cvs-lotte-uiseong-garlic-spicy-frank-70',
  'cvs-cj-maxbon-original-50',
  'cvs-lotte-kisseutik-original-50',
  'cvs-cj-spam-single-classic-80',
  'cvs-sajo-spicy-hotbar-80',
  'cvs-lotte-chilsung-cider-zero-355',
  'cvs-cocacola-zero-355',
  'cvs-pepsi-zero-lime-355',
  'cvs-binggrae-banana-milk-light-240',
  'cvs-maeil-baristarules-latte-250',
  'cvs-kwangdong-vita500-zero-100',
  'cvs-lotte-worldcone-vanilla-160',
  'cvs-lotte-jawsbar-75',
  'cvs-lotte-screwbar-75',
  'cvs-binggrae-babamba-70',
  'cvs-hbaf-honey-butter-almond-30',
  'cvs-hbaf-wasabi-almond-30',
  'cvs-orion-chocopie-single-39',
  'cvs-lotte-chicchoc-single-30',
  'cvs-nongshim-bbusheo-bbusheo-bulgogi-90',
  'cvs-pulmuone-chokchokran-egg-100',
  'cvs-cj-cupban-miyeokguk-167',
  'cvs-cj-cupban-hwangtaeguk-170'
]);

// 기존 seed에서 신규 37개 제거 후 정상화된 값으로 다시 추가
const baseSeed = seed.filter(s => !newIds.has(s.menu_id));

const newCvsItems = [
  // 1. 컵라면 (7종)
  {
    menu_id: 'cvs-nongshim-neoguri-bowl-111',
    channel: 'cvs',
    brand: '농심',
    name: '농심 너구리 큰사발면 111g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 111,
    kcal: 515,
    protein_g: 9,
    carb_g: 82,
    sugar_g: 5,
    fat_g: 17,
    sat_fat_g: 8,
    sodium_mg: 1550,
    protein_source: 'Q3',
    cooking: 'boil',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043003017',
    source_type: 'T2',
    source_url: 'https://www.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/J0SCluxzYV9'
  },
  {
    menu_id: 'cvs-ottogi-chamkkae-ramen-cup-110',
    channel: 'cvs',
    brand: '오뚜기',
    name: '오뚜기 참깨라면 큰사발 110g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 110,
    kcal: 490,
    protein_g: 10,
    carb_g: 72,
    sugar_g: 4,
    fat_g: 18,
    sat_fat_g: 8,
    sodium_mg: 1690,
    protein_source: 'Q3',
    cooking: 'boil',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801045521021',
    source_type: 'T2',
    source_url: 'https://www.ottogi.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/IH5BAa9fD5Z'
  },
  {
    menu_id: 'cvs-ottogi-yeol-ramen-cup-105',
    channel: 'cvs',
    brand: '오뚜기',
    name: '오뚜기 열라면 큰사발 105g',
    category: '라면/면류',
    price_krw: 1400,
    serving_g: 105,
    kcal: 465,
    protein_g: 9,
    carb_g: 71,
    sugar_g: 4,
    fat_g: 16,
    sat_fat_g: 8,
    sodium_mg: 1650,
    protein_source: 'Q3',
    cooking: 'boil',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801045521052',
    source_type: 'T2',
    source_url: 'https://www.ottogi.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/2zVo9pY5cSc'
  },
  {
    menu_id: 'cvs-paldo-wangttukkeong-110',
    channel: 'cvs',
    brand: '팔도',
    name: '팔도 왕뚜껑 110g',
    category: '라면/면류',
    price_krw: 1400,
    serving_g: 110,
    kcal: 475,
    protein_g: 9,
    carb_g: 74,
    sugar_g: 4,
    fat_g: 16,
    sat_fat_g: 8,
    sodium_mg: 1690,
    protein_source: 'Q3',
    cooking: 'boil',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801128503058',
    source_type: 'T2',
    source_url: 'https://www.paldofood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/Kc1dQ6TtI7m'
  },
  {
    menu_id: 'cvs-gs25-omori-kimchi-stew-cup-160',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 오모리 김치찌개라면 160g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 160,
    kcal: 485,
    protein_g: 10,
    carb_g: 75,
    sugar_g: 6,
    fat_g: 16,
    sat_fat_g: 7,
    sodium_mg: 1870,
    protein_source: 'Q3',
    cooking: 'boil',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801128516102',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/7ZtYhY8UNwt'
  },
  {
    menu_id: 'cvs-samyang-cheese-buldak-cup-105',
    channel: 'cvs',
    brand: '삼양식품',
    name: '삼양 치즈 불닭볶음면 큰컵 105g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 105,
    kcal: 430,
    protein_g: 8,
    carb_g: 68,
    sugar_g: 7,
    fat_g: 14,
    sat_fat_g: 7,
    sodium_mg: 1300,
    protein_source: 'Q3',
    cooking: 'boil',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801073210744',
    source_type: 'T2',
    source_url: 'https://www.samyangfoods.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/4IZX6mjhtR4'
  },
  {
    menu_id: 'cvs-nongshim-ansungtangmyun-cup-66',
    channel: 'cvs',
    brand: '농심',
    name: '농심 안성탕면 컵 66g',
    category: '라면/면류',
    price_krw: 1200,
    serving_g: 66,
    kcal: 280,
    protein_g: 5,
    carb_g: 43,
    sugar_g: 3,
    fat_g: 10,
    sat_fat_g: 5,
    sodium_mg: 1190,
    protein_source: 'Q3',
    cooking: 'boil',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043015843',
    source_type: 'T2',
    source_url: 'https://www.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/H3ZZw6tJeJO'
  },

  // 2. 샌드위치 & 햄버거 (6종)
  {
    menu_id: 'cvs-gs25-idol-popular-sandwich-150',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 아이돌 인기 샌드위치 150g',
    category: '샌드위치/버거',
    price_krw: 2800,
    serving_g: 150,
    kcal: 385,
    protein_g: 9,
    carb_g: 49,
    sugar_g: 12,
    fat_g: 17,
    sat_fat_g: 4.5,
    sodium_mg: 720,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809282361118',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/1p0tooE6KdL'
  },
  {
    menu_id: 'cvs-gs25-double-bulgogi-burger-190',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 더블 불고기버거 190g',
    category: '샌드위치/버거',
    price_krw: 3200,
    serving_g: 190,
    kcal: 480,
    protein_g: 18,
    carb_g: 52,
    sugar_g: 11,
    fat_g: 22,
    sat_fat_g: 8,
    sodium_mg: 980,
    protein_source: 'Q2',
    cooking: 'microwave',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809282362245',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/4X5Mf29LFgZ'
  },
  {
    menu_id: 'cvs-cu-taiwan-condensed-milk-sandwich-130',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 대만식 연유 샌드위치 130g',
    category: '샌드위치/버거',
    price_krw: 2500,
    serving_g: 130,
    kcal: 310,
    protein_g: 7,
    carb_g: 39,
    sugar_g: 14,
    fat_g: 14,
    sat_fat_g: 5,
    sodium_mg: 430,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809623841028',
    source_type: 'T2',
    source_url: 'https://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/KIOdOZJUUQk'
  },
  {
    menu_id: 'cvs-cu-spicy-chicken-burger-180',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 매콤 치킨버거 180g',
    category: '샌드위치/버거',
    price_krw: 3400,
    serving_g: 180,
    kcal: 490,
    protein_g: 19,
    carb_g: 51,
    sugar_g: 10,
    fat_g: 23,
    sat_fat_g: 7,
    sodium_mg: 950,
    protein_source: 'Q1',
    cooking: 'microwave',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809623842155',
    source_type: 'T2',
    source_url: 'https://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/IClmSF0bQ3q'
  },
  {
    menu_id: 'cvs-seven-bulgogi-burger-175',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '세븐일레븐 불고기 버거 175g',
    category: '샌드위치/버거',
    price_krw: 2900,
    serving_g: 175,
    kcal: 420,
    protein_g: 15,
    carb_g: 50,
    sugar_g: 9,
    fat_g: 18,
    sat_fat_g: 6,
    sodium_mg: 840,
    protein_source: 'Q2',
    cooking: 'microwave',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809187321045',
    source_type: 'T2',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/66nzTTdxW8m'
  },
  {
    menu_id: 'cvs-seven-egg-potato-sandwich-160',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '세븐일레븐 에그 포테이토 샌드위치 160g',
    category: '샌드위치/버거',
    price_krw: 2700,
    serving_g: 160,
    kcal: 340,
    protein_g: 8,
    carb_g: 41,
    sugar_g: 7,
    fat_g: 16,
    sat_fat_g: 4,
    sodium_mg: 580,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809187322158',
    source_type: 'T2',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/4RsvXhG8Sgo'
  },

  // 3. 핫바 & 소시지 (6종)
  {
    menu_id: 'cvs-lotte-uiseong-garlic-frank-70',
    channel: 'cvs',
    brand: '롯데웰푸드',
    name: '롯데 의성마늘 후랑크 70g',
    category: '닭가슴살/육가공',
    price_krw: 2200,
    serving_g: 70,
    kcal: 195,
    protein_g: 9,
    carb_g: 6,
    sugar_g: 2,
    fat_g: 15,
    sat_fat_g: 5,
    sodium_mg: 510,
    protein_source: 'Q2',
    cooking: 'microwave',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801062634018',
    source_type: 'T2',
    source_url: 'https://www.lottewellfood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/DT3jRvjxJZk'
  },
  {
    menu_id: 'cvs-lotte-uiseong-garlic-spicy-frank-70',
    channel: 'cvs',
    brand: '롯데웰푸드',
    name: '롯데 의성마늘 매콤 후랑크 70g',
    category: '닭가슴살/육가공',
    price_krw: 2200,
    serving_g: 70,
    kcal: 190,
    protein_g: 9,
    carb_g: 7,
    sugar_g: 2,
    fat_g: 14,
    sat_fat_g: 5,
    sodium_mg: 530,
    protein_source: 'Q2',
    cooking: 'microwave',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801062634025',
    source_type: 'T2',
    source_url: 'https://www.lottewellfood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/3SS21vlmxMx'
  },
  {
    menu_id: 'cvs-cj-maxbon-original-50',
    channel: 'cvs',
    brand: 'CJ제일제당',
    name: 'CJ 맥스봉 오리지널 소시지 50g',
    category: '닭가슴살/육가공',
    price_krw: 1700,
    serving_g: 50,
    kcal: 95,
    protein_g: 5,
    carb_g: 8,
    sugar_g: 2,
    fat_g: 5,
    sat_fat_g: 1.8,
    sodium_mg: 340,
    protein_source: 'Q2',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801007052952',
    source_type: 'T2',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/LdKexXeKjbK'
  },
  {
    menu_id: 'cvs-lotte-kisseutik-original-50',
    channel: 'cvs',
    brand: '롯데웰푸드',
    name: '롯데 키스틱 오리지널 50g',
    category: '닭가슴살/육가공',
    price_krw: 1600,
    serving_g: 50,
    kcal: 85,
    protein_g: 4,
    carb_g: 8,
    sugar_g: 2,
    fat_g: 4,
    sat_fat_g: 1.5,
    sodium_mg: 310,
    protein_source: 'Q2',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801062630119',
    source_type: 'T2',
    source_url: 'https://www.lottewellfood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/2PG1ZPPCu9x'
  },
  {
    menu_id: 'cvs-cj-spam-single-classic-80',
    channel: 'cvs',
    brand: 'CJ제일제당',
    name: 'CJ 스팸 싱글 클래식 80g',
    category: '닭가슴살/육가공',
    price_krw: 2600,
    serving_g: 80,
    kcal: 260,
    protein_g: 11,
    carb_g: 2,
    sugar_g: 1,
    fat_g: 23,
    sat_fat_g: 8,
    sodium_mg: 820,
    protein_source: 'Q2',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801007137024',
    source_type: 'T2',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/IWs6Kxj0u5D'
  },
  {
    menu_id: 'cvs-sajo-spicy-hotbar-80',
    channel: 'cvs',
    brand: '사조대림',
    name: '사조 대림선 매콤 숯불구이맛 핫바 80g',
    category: '닭가슴살/육가공',
    price_krw: 2300,
    serving_g: 80,
    kcal: 160,
    protein_g: 10,
    carb_g: 12,
    sugar_g: 3,
    fat_g: 8,
    sat_fat_g: 2.5,
    sodium_mg: 590,
    protein_source: 'Q2',
    cooking: 'microwave',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801077224013',
    source_type: 'T2',
    source_url: 'https://www.sajo.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/G3oiBtJSfsq'
  },

  // 4. 제로 음료 & 편의점 음료 (6종)
  {
    menu_id: 'cvs-lotte-chilsung-cider-zero-355',
    channel: 'cvs',
    brand: '롯데칠성',
    name: '롯데 칠성사이다 제로 355mL',
    category: '유제품/음료',
    price_krw: 1900,
    serving_g: 355,
    kcal: 2,
    protein_g: 0,
    carb_g: 0.5,
    sugar_g: 0,
    fat_g: 0,
    sat_fat_g: 0,
    sodium_mg: 10,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 1,
    claim_text: '칼로리 ZERO',
    barcode: '8801056012433',
    source_type: 'T2',
    source_url: 'https://company.lottechilsung.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/CcZlwbouky0'
  },
  {
    menu_id: 'cvs-cocacola-zero-355',
    channel: 'cvs',
    brand: '코카콜라',
    name: '코카콜라 제로 355mL',
    category: '유제품/음료',
    price_krw: 2000,
    serving_g: 355,
    kcal: 2,
    protein_g: 0,
    carb_g: 0.5,
    sugar_g: 0,
    fat_g: 0,
    sat_fat_g: 0,
    sodium_mg: 15,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 1,
    claim_text: 'ZERO Sugar ZERO Calorie',
    barcode: '8801094017200',
    source_type: 'T2',
    source_url: 'https://www.coca-cola.com/kr/ko',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/L73YRIBEIln'
  },
  {
    menu_id: 'cvs-pepsi-zero-lime-355',
    channel: 'cvs',
    brand: '롯데칠성',
    name: '롯데 펩시 제로슈거 라임향 355mL',
    category: '유제품/음료',
    price_krw: 1900,
    serving_g: 355,
    kcal: 2,
    protein_g: 0,
    carb_g: 0.5,
    sugar_g: 0,
    fat_g: 0,
    sat_fat_g: 0,
    sodium_mg: 40,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 1,
    claim_text: 'ZERO Sugar 라임향',
    barcode: '8801056023019',
    source_type: 'T2',
    source_url: 'https://company.lottechilsung.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/IKHnHf8RnyL'
  },
  {
    menu_id: 'cvs-binggrae-banana-milk-light-240',
    channel: 'cvs',
    brand: '빙그레',
    name: '빙그레 바나나맛우유 라이트 240mL',
    category: '유제품/음료',
    price_krw: 1800,
    serving_g: 240,
    kcal: 142,
    protein_g: 6.5,
    carb_g: 24,
    sugar_g: 21,
    fat_g: 2.0,
    sat_fat_g: 1.3,
    sodium_mg: 95,
    protein_source: 'Q1',
    cooking: 'raw',
    marketing_claim: 1,
    claim_text: '지방을 낮춘 라이트',
    barcode: '8801104641012',
    source_type: 'T2',
    source_url: 'https://www.bing.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/7NsFFKBZvCR'
  },
  {
    menu_id: 'cvs-maeil-baristarules-latte-250',
    channel: 'cvs',
    brand: '매일유업',
    name: '매일유업 바리스타룰스 로에스프레소 라떼 250mL',
    category: '유제품/음료',
    price_krw: 2500,
    serving_g: 250,
    kcal: 155,
    protein_g: 5,
    carb_g: 22,
    sugar_g: 19,
    fat_g: 5,
    sat_fat_g: 3.5,
    sodium_mg: 130,
    protein_source: 'Q1',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801121021484',
    source_type: 'T2',
    source_url: 'https://www.maeil.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/45d8C7iXbIT'
  },
  {
    menu_id: 'cvs-kwangdong-vita500-zero-100',
    channel: 'cvs',
    brand: '광동제약',
    name: '광동 비타500 제로 100mL',
    category: '유제품/음료',
    price_krw: 1100,
    serving_g: 100,
    kcal: 2,
    protein_g: 0,
    carb_g: 0.5,
    sugar_g: 0,
    fat_g: 0,
    sat_fat_g: 0,
    sodium_mg: 10,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 1,
    claim_text: '비타민C 500mg 당류 0g 칼로리 ZERO',
    barcode: '8806002014120',
    source_type: 'T2',
    source_url: 'https://www.ekdp.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/BeIBjLjg5PE'
  },

  // 5. 아이스크림 & 빙과 (4종)
  {
    menu_id: 'cvs-lotte-worldcone-vanilla-160',
    channel: 'cvs',
    brand: '롯데웰푸드',
    name: '롯데 월드콘 바닐라 160mL',
    category: '아이스크림',
    price_krw: 2200,
    serving_g: 160,
    kcal: 255,
    protein_g: 4,
    carb_g: 33,
    sugar_g: 22,
    fat_g: 12,
    sat_fat_g: 8,
    sodium_mg: 65,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801062514013',
    source_type: 'T2',
    source_url: 'https://www.lottewellfood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/CsXVxadhjf'
  },
  {
    menu_id: 'cvs-lotte-jawsbar-75',
    channel: 'cvs',
    brand: '롯데웰푸드',
    name: '롯데 죠스바 75mL',
    category: '아이스크림',
    price_krw: 1200,
    serving_g: 75,
    kcal: 85,
    protein_g: 0,
    carb_g: 21,
    sugar_g: 15,
    fat_g: 0,
    sat_fat_g: 0,
    sodium_mg: 10,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801062518011',
    source_type: 'T2',
    source_url: 'https://www.lottewellfood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/5dX1FTp3WIe'
  },
  {
    menu_id: 'cvs-lotte-screwbar-75',
    channel: 'cvs',
    brand: '롯데웰푸드',
    name: '롯데 스크류바 75mL',
    category: '아이스크림',
    price_krw: 1200,
    serving_g: 75,
    kcal: 85,
    protein_g: 0,
    carb_g: 21,
    sugar_g: 15,
    fat_g: 0,
    sat_fat_g: 0,
    sodium_mg: 10,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801062518028',
    source_type: 'T2',
    source_url: 'https://www.lottewellfood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/HszVeuWbi3b'
  },
  {
    menu_id: 'cvs-binggrae-babamba-70',
    channel: 'cvs',
    brand: '빙그레',
    name: '빙그레 바밤바 70mL',
    category: '아이스크림',
    price_krw: 1200,
    serving_g: 70,
    kcal: 95,
    protein_g: 1,
    carb_g: 17,
    sugar_g: 13,
    fat_g: 2.5,
    sat_fat_g: 1.6,
    sodium_mg: 40,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801104230117',
    source_type: 'T2',
    source_url: 'https://www.bing.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/FGXYt9r7yYL'
  },

  // 6. 견과 & 스낵 (5종)
  {
    menu_id: 'cvs-hbaf-honey-butter-almond-30',
    channel: 'cvs',
    brand: '바프',
    name: '바프 HBAF 허니버터아몬드 30g',
    category: '과자/바',
    price_krw: 1500,
    serving_g: 30,
    kcal: 170,
    protein_g: 5.5,
    carb_g: 10,
    sugar_g: 5,
    fat_g: 12,
    sat_fat_g: 1.0,
    sodium_mg: 85,
    protein_source: 'Q2',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809441430114',
    source_type: 'T2',
    source_url: 'https://www.hbaf.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/LF6sm6SxU6p'
  },
  {
    menu_id: 'cvs-hbaf-wasabi-almond-30',
    channel: 'cvs',
    brand: '바프',
    name: '바프 HBAF 와사비맛아몬드 30g',
    category: '과자/바',
    price_krw: 1500,
    serving_g: 30,
    kcal: 170,
    protein_g: 5.5,
    carb_g: 10,
    sugar_g: 5,
    fat_g: 12,
    sat_fat_g: 1.0,
    sodium_mg: 110,
    protein_source: 'Q2',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809441430121',
    source_type: 'T2',
    source_url: 'https://www.hbaf.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/4qRvfzIkM2k'
  },
  {
    menu_id: 'cvs-orion-chocopie-single-39',
    channel: 'cvs',
    brand: '오리온',
    name: '오리온 초코파이 情 39g',
    category: '과자/바',
    price_krw: 600,
    serving_g: 39,
    kcal: 171,
    protein_g: 2,
    carb_g: 25,
    sugar_g: 14,
    fat_g: 7,
    sat_fat_g: 4.6,
    sodium_mg: 90,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801117111014',
    source_type: 'T2',
    source_url: 'https://www.orionworld.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/9MKN0MdspPh'
  },
  {
    menu_id: 'cvs-lotte-chicchoc-single-30',
    channel: 'cvs',
    brand: '롯데웰푸드',
    name: '롯데 칙촉 오리지널 30g',
    category: '과자/바',
    price_krw: 1000,
    serving_g: 30,
    kcal: 150,
    protein_g: 2,
    carb_g: 18,
    sugar_g: 11,
    fat_g: 8,
    sat_fat_g: 4.3,
    sodium_mg: 85,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801062637019',
    source_type: 'T2',
    source_url: 'https://www.lottewellfood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/DS9os5jGqtt'
  },
  {
    menu_id: 'cvs-nongshim-bbusheo-bbusheo-bulgogi-90',
    channel: 'cvs',
    brand: '농심',
    name: '농심 뿌셔뿌셔 불고기맛 90g',
    category: '과자/바',
    price_krw: 1200,
    serving_g: 90,
    kcal: 415,
    protein_g: 7,
    carb_g: 63,
    sugar_g: 6,
    fat_g: 15,
    sat_fat_g: 8,
    sodium_mg: 720,
    protein_source: 'Q3',
    cooking: 'raw',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043015409',
    source_type: 'T2',
    source_url: 'https://www.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/GEbYbBfXl86'
  },

  // 7. 계란 & 간편 국밥 (3종)
  {
    menu_id: 'cvs-pulmuone-chokchokran-egg-100',
    channel: 'cvs',
    brand: '풀무원',
    name: '풀무원 촉촉란 2구 100g',
    category: '닭가슴살/육가공',
    price_krw: 2400,
    serving_g: 100,
    kcal: 130,
    protein_g: 12,
    carb_g: 1,
    sugar_g: 0,
    fat_g: 8.5,
    sat_fat_g: 2.8,
    sodium_mg: 340,
    protein_source: 'Q1',
    cooking: 'boil',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801114138014',
    source_type: 'T2',
    source_url: 'https://www.pulmuone.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/1HHYIfqoIzz'
  },
  {
    menu_id: 'cvs-cj-cupban-miyeokguk-167',
    channel: 'cvs',
    brand: 'CJ제일제당',
    name: 'CJ 햇반컵반 미역국밥 167g',
    category: '도시락',
    price_krw: 3900,
    serving_g: 167,
    kcal: 220,
    protein_g: 5,
    carb_g: 45,
    sugar_g: 1,
    fat_g: 2.5,
    sat_fat_g: 0.5,
    sodium_mg: 890,
    protein_source: 'Q3',
    cooking: 'microwave',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801007421116',
    source_type: 'T2',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/Gz9L5ZRyEET'
  },
  {
    menu_id: 'cvs-cj-cupban-hwangtaeguk-170',
    channel: 'cvs',
    brand: 'CJ제일제당',
    name: 'CJ 햇반컵반 황태국밥 170g',
    category: '도시락',
    price_krw: 3900,
    serving_g: 170,
    kcal: 235,
    protein_g: 7,
    carb_g: 47,
    sugar_g: 1,
    fat_g: 2.0,
    sat_fat_g: 0.5,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'microwave',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801007421123',
    source_type: 'T2',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0',
    image_url: 'https://search4.kakaocdn.net/argon/320x320_85_c/Jm0dAzyQjON'
  }
];

const finalSeed = [...baseSeed, ...newCvsItems];
console.log(`Base seed: ${baseSeed.length}, New: ${newCvsItems.length}, Total: ${finalSeed.length}`);
fs.writeFileSync(seedPath, JSON.stringify(finalSeed, null, 2), 'utf-8');
console.log('Successfully updated data/seed.json with calibrated zero beverage kcal!');
