// scripts/add_franchise_batch2.js
// 외식 프랜차이즈 2차 확장 (치킨, 버거, 한솥 도시락, 키토 김밥, 멕시칸 볼, 카페 고단백 샌드위치) 46개 신규 품목
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { validateMenuQA } from '../js/qa.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

export const newFranchiseItems = [
  // ─────────────────────────────────────────────────────────────
  // 1. 굽네치킨 (5개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-goobne-original-boneless-200',
    channel: 'fr',
    brand: '굽네치킨',
    name: '굽네 오리지널 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 9500,
    serving_g: 200,
    kcal: 420,
    protein_g: 48.0,
    carb_g: 2.0,
    sugar_g: 0.5,
    fat_g: 24.0,
    sat_fat_g: 6.0,
    sodium_mg: 780,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '오븐에 구운 순살 1회 단백질 48g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.goobne.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-goobne-pepper-crispy-boneless-200',
    channel: 'fr',
    brand: '굽네치킨',
    name: '굽네 고추바사삭 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 10000,
    serving_g: 200,
    kcal: 450,
    protein_g: 44.0,
    carb_g: 14.0,
    sugar_g: 2.0,
    fat_g: 24.0,
    sat_fat_g: 5.5,
    sodium_mg: 880,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '매콤 바삭 오븐구이 단백질 44g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.goobne.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-goobne-volcano-boneless-200',
    channel: 'fr',
    brand: '굽네치킨',
    name: '굽네 볼케이노 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 10000,
    serving_g: 200,
    kcal: 430,
    protein_g: 46.0,
    carb_g: 12.0,
    sugar_g: 6.0,
    fat_g: 22.0,
    sat_fat_g: 5.2,
    sodium_mg: 960,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.goobne.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-goobne-garlic-crispy-boneless-200',
    channel: 'fr',
    brand: '굽네치킨',
    name: '굽네 남해마늘 바사삭 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 10500,
    serving_g: 200,
    kcal: 460,
    protein_g: 43.0,
    carb_g: 16.0,
    sugar_g: 3.0,
    fat_g: 25.0,
    sat_fat_g: 5.8,
    sodium_mg: 890,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.goobne.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-goobne-chicken-breast-vienna-120',
    channel: 'fr',
    brand: '굽네치킨',
    name: '굽네 닭가슴살 그릴 비엔나 120g',
    category: '닭가슴살/육가공',
    price_krw: 3500,
    serving_g: 120,
    kcal: 210,
    protein_g: 22.0,
    carb_g: 4.0,
    sugar_g: 2.0,
    fat_g: 11.5,
    sat_fat_g: 3.5,
    sodium_mg: 490,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '육즙 가득 닭가슴살 소시지 단백질 22g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.goobne.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 2. 교촌치킨, BBQ, BHC (6개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-kyochon-original-boneless-200',
    channel: 'fr',
    brand: '교촌치킨',
    name: '교촌 오리지널 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 10500,
    serving_g: 200,
    kcal: 520,
    protein_g: 46.0,
    carb_g: 18.0,
    sugar_g: 4.0,
    fat_g: 29.0,
    sat_fat_g: 6.2,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kyochon.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kyochon-red-boneless-200',
    channel: 'fr',
    brand: '교촌치킨',
    name: '교촌 레드 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11000,
    serving_g: 200,
    kcal: 535,
    protein_g: 45.0,
    carb_g: 20.0,
    sugar_g: 6.0,
    fat_g: 30.0,
    sat_fat_g: 6.5,
    sodium_mg: 980,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kyochon.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kyochon-honey-boneless-200',
    channel: 'fr',
    brand: '교촌치킨',
    name: '교촌 허니 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11500,
    serving_g: 200,
    kcal: 560,
    protein_g: 42.0,
    carb_g: 28.0,
    sugar_g: 12.0,
    fat_g: 31.0,
    sat_fat_g: 6.8,
    sodium_mg: 850,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kyochon.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-bbq-jamaica-whole-thigh-220',
    channel: 'fr',
    brand: 'BBQ',
    name: '자메이카 통다리구이 2조각 (220g)',
    category: '닭가슴살/육가공',
    price_krw: 11000,
    serving_g: 220,
    kcal: 430,
    protein_g: 44.0,
    carb_g: 8.0,
    sugar_g: 4.0,
    fat_g: 24.0,
    sat_fat_g: 6.5,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '저크소스 오븐 통다리구이 단백질 44g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.bbq.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-bbq-golden-olive-boneless-200',
    channel: 'fr',
    brand: 'BBQ',
    name: '황금올리브치킨 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11000,
    serving_g: 200,
    kcal: 540,
    protein_g: 38.0,
    carb_g: 22.0,
    sugar_g: 2.0,
    fat_g: 33.0,
    sat_fat_g: 7.2,
    sodium_mg: 890,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.bbq.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-bhc-matchoking-boneless-200',
    channel: 'fr',
    brand: 'BHC',
    name: '맛초킹 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11000,
    serving_g: 200,
    kcal: 510,
    protein_g: 40.0,
    carb_g: 24.0,
    sugar_g: 8.0,
    fat_g: 28.0,
    sat_fat_g: 5.8,
    sodium_mg: 940,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.bhc.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 3. 롯데리아 (6개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-lotteria-t-rex-burger-214',
    channel: 'fr',
    brand: '롯데리아',
    name: 'T-REX 버거 단품 214g',
    category: '샌드위치/버거',
    price_krw: 4700,
    serving_g: 214,
    kcal: 475,
    protein_g: 26.0,
    carb_g: 53.0,
    sugar_g: 8.0,
    fat_g: 18.0,
    sat_fat_g: 4.5,
    sodium_mg: 875,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '큼직한 통다리살 치킨 패티 단백질 26g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-lotteria-hot-crispy-burger-189',
    channel: 'fr',
    brand: '롯데리아',
    name: '핫크리스피 버거 단품 189g',
    category: '샌드위치/버거',
    price_krw: 5900,
    serving_g: 189,
    kcal: 503,
    protein_g: 22.0,
    carb_g: 58.0,
    sugar_g: 7.0,
    fat_g: 20.0,
    sat_fat_g: 4.8,
    sodium_mg: 934,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-lotteria-classic-cheese-burger-145',
    channel: 'fr',
    brand: '롯데리아',
    name: '클래식 치즈버거 단품 145g',
    category: '샌드위치/버거',
    price_krw: 5200,
    serving_g: 145,
    kcal: 483,
    protein_g: 20.0,
    carb_g: 36.0,
    sugar_g: 6.0,
    fat_g: 28.0,
    sat_fat_g: 12.0,
    sodium_mg: 792,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-lotteria-hanwoo-bulgogi-burger-266',
    channel: 'fr',
    brand: '롯데리아',
    name: '한우불고기 버거 단품 266g',
    category: '샌드위치/버거',
    price_krw: 8400,
    serving_g: 266,
    kcal: 572,
    protein_g: 26.0,
    carb_g: 63.0,
    sugar_g: 14.0,
    fat_g: 24.0,
    sat_fat_g: 9.0,
    sodium_mg: 928,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-lotteria-mozzarella-in-the-burger-bacon-224',
    channel: 'fr',
    brand: '롯데리아',
    name: '모짜렐라 인 더 버거 베이컨 단품 224g',
    category: '샌드위치/버거',
    price_krw: 7700,
    serving_g: 224,
    kcal: 715,
    protein_g: 31.0,
    carb_g: 59.0,
    sugar_g: 6.0,
    fat_g: 39.0,
    sat_fat_g: 15.0,
    sodium_mg: 1025,
    protein_source: 'Q1',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '자연산 모짜렐라 치즈와 베이컨 단백질 31g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-lotteria-chicken-fillet-4pcs-116',
    channel: 'fr',
    brand: '롯데리아',
    name: '치킨 휠레 4조각 116g',
    category: '닭가슴살/육가공',
    price_krw: 4700,
    serving_g: 116,
    kcal: 204,
    protein_g: 22.0,
    carb_g: 10.0,
    sugar_g: 0.5,
    fat_g: 8.4,
    sat_fat_g: 2.1,
    sodium_mg: 586,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '담백한 안심살 순살 휠레 단백질 22g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 4. 노브랜드버거 (5개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-nbb-signature-burger-203',
    channel: 'fr',
    brand: '노브랜드버거',
    name: 'NBB 시그니처 버거 단품 203g',
    category: '샌드위치/버거',
    price_krw: 4800,
    serving_g: 203,
    kcal: 532,
    protein_g: 21.0,
    carb_g: 47.0,
    sugar_g: 8.0,
    fat_g: 29.0,
    sat_fat_g: 9.0,
    sodium_mg: 987,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.shinsegaefood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-nbb-coleslaw-chicken-burger-226',
    channel: 'fr',
    brand: '노브랜드버거',
    name: '코울슬로 치킨 버거 단품 226g',
    category: '샌드위치/버거',
    price_krw: 4700,
    serving_g: 226,
    kcal: 531,
    protein_g: 24.0,
    carb_g: 56.0,
    sugar_g: 12.0,
    fat_g: 23.0,
    sat_fat_g: 4.8,
    sodium_mg: 1120,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '두툼한 통치킨 패티와 코울슬로 단백질 24g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.shinsegaefood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-nbb-megabyte-burger-252',
    channel: 'fr',
    brand: '노브랜드버거',
    name: '메가바이트 버거 단품 252g',
    category: '샌드위치/버거',
    price_krw: 5000,
    serving_g: 252,
    kcal: 660,
    protein_g: 22.0,
    carb_g: 68.0,
    sugar_g: 8.0,
    fat_g: 33.0,
    sat_fat_g: 9.0,
    sodium_mg: 1220,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.shinsegaefood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-nbb-grilled-bulgogi-burger-154',
    channel: 'fr',
    brand: '노브랜드버거',
    name: '그릴드 불고기 버거 단품 154g',
    category: '샌드위치/버거',
    price_krw: 2900,
    serving_g: 154,
    kcal: 426,
    protein_g: 15.0,
    carb_g: 49.0,
    sugar_g: 11.0,
    fat_g: 19.0,
    sat_fat_g: 6.0,
    sodium_mg: 796,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.shinsegaefood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-nbb-crunch-wing-4pcs-120',
    channel: 'fr',
    brand: '노브랜드버거',
    name: '크런치 윙 4조각 120g',
    category: '닭가슴살/육가공',
    price_krw: 5400,
    serving_g: 120,
    kcal: 335,
    protein_g: 20.0,
    carb_g: 14.0,
    sugar_g: 1.0,
    fat_g: 22.0,
    sat_fat_g: 5.5,
    sodium_mg: 720,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.shinsegaefood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 5. 프랭크버거 (4개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-frankburger-frank-burger-r-170',
    channel: 'fr',
    brand: '프랭크버거',
    name: '프랭크버거 R 단품 170g',
    category: '샌드위치/버거',
    price_krw: 4600,
    serving_g: 170,
    kcal: 496,
    protein_g: 18.0,
    carb_g: 42.0,
    sugar_g: 8.0,
    fat_g: 28.0,
    sat_fat_g: 9.0,
    sodium_mg: 780,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://frankburger.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-frankburger-cheeseburger-r-190',
    channel: 'fr',
    brand: '프랭크버거',
    name: '치즈버거 R 단품 190g',
    category: '샌드위치/버거',
    price_krw: 5500,
    serving_g: 190,
    kcal: 535,
    protein_g: 21.0,
    carb_g: 43.0,
    sugar_g: 8.0,
    fat_g: 31.0,
    sat_fat_g: 12.0,
    sodium_mg: 890,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://frankburger.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-frankburger-double-cheeseburger-r-260',
    channel: 'fr',
    brand: '프랭크버거',
    name: '더블치즈버거 R 단품 260g',
    category: '샌드위치/버거',
    price_krw: 7900,
    serving_g: 260,
    kcal: 715,
    protein_g: 35.0,
    carb_g: 44.0,
    sugar_g: 9.0,
    fat_g: 44.0,
    sat_fat_g: 18.0,
    sodium_mg: 1150,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '순쇠고기 패티 2장 단백질 35g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://frankburger.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-frankburger-jg-burger-310',
    channel: 'fr',
    brand: '프랭크버거',
    name: 'JG버거 단품 310g',
    category: '샌드위치/버거',
    price_krw: 9300,
    serving_g: 310,
    kcal: 860,
    protein_g: 44.0,
    carb_g: 46.0,
    sugar_g: 9.0,
    fat_g: 55.0,
    sat_fat_g: 22.0,
    sodium_mg: 1390,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '순쇠고기 패티 2장 베이컨 단백질 44g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://frankburger.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 6. 한솥도시락 (7개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-hansot-chicken-mayo-301',
    channel: 'fr',
    brand: '한솥도시락',
    name: '치킨마요 301g',
    category: '도시락',
    price_krw: 3800,
    serving_g: 301,
    kcal: 453,
    protein_g: 17.0,
    carb_g: 68.0,
    sugar_g: 6.0,
    fat_g: 12.5,
    sat_fat_g: 2.8,
    sodium_mg: 790,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-big-chicken-mayo-395',
    channel: 'fr',
    brand: '한솥도시락',
    name: '빅치킨마요 395g',
    category: '도시락',
    price_krw: 4400,
    serving_g: 395,
    kcal: 595,
    protein_g: 23.0,
    carb_g: 88.0,
    sugar_g: 8.0,
    fat_g: 16.5,
    sat_fat_g: 3.5,
    sodium_mg: 980,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-tonkatsu-doryeonnim-390',
    channel: 'fr',
    brand: '한솥도시락',
    name: '돈까스도련님 도시락 390g',
    category: '도시락',
    price_krw: 4900,
    serving_g: 390,
    kcal: 640,
    protein_g: 26.0,
    carb_g: 85.0,
    sugar_g: 7.0,
    fat_g: 21.5,
    sat_fat_g: 5.5,
    sodium_mg: 1050,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-dongbaek-dosirak-440',
    channel: 'fr',
    brand: '한솥도시락',
    name: '동백 도시락 440g',
    category: '도시락',
    price_krw: 6000,
    serving_g: 440,
    kcal: 720,
    protein_g: 29.0,
    carb_g: 92.0,
    sugar_g: 8.0,
    fat_g: 25.5,
    sat_fat_g: 6.2,
    sodium_mg: 1180,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-spicy-pork-dosirak-380',
    channel: 'fr',
    brand: '한솥도시락',
    name: '제육볶음 도시락 380g',
    category: '도시락',
    price_krw: 4900,
    serving_g: 380,
    kcal: 620,
    protein_g: 27.0,
    carb_g: 82.0,
    sugar_g: 9.0,
    fat_g: 20.0,
    sat_fat_g: 5.8,
    sodium_mg: 1120,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-mega-chicken-pork-560',
    channel: 'fr',
    brand: '한솥도시락',
    name: '메가치킨제육 도시락 560g',
    category: '도시락',
    price_krw: 7700,
    serving_g: 560,
    kcal: 915,
    protein_g: 44.0,
    carb_g: 110.0,
    sugar_g: 12.0,
    fat_g: 32.5,
    sat_fat_g: 8.5,
    sodium_mg: 1540,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '치킨가라아게와 제육볶음 단백질 44g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-charcoal-bulgogi-bowl-350',
    channel: 'fr',
    brand: '한솥도시락',
    name: '숯불직화구이 덮밥 350g',
    category: '도시락',
    price_krw: 6000,
    serving_g: 350,
    kcal: 550,
    protein_g: 24.0,
    carb_g: 75.0,
    sugar_g: 11.0,
    fat_g: 16.5,
    sat_fat_g: 4.8,
    sodium_mg: 990,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 7. 바르다김선생 & 쿠차라 (6개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-teacherkim-bareun-gimbap-250',
    channel: 'fr',
    brand: '바르다김선생',
    name: '바른 김밥 250g',
    category: '도시락',
    price_krw: 4500,
    serving_g: 250,
    kcal: 385,
    protein_g: 14.0,
    carb_g: 58.0,
    sugar_g: 5.0,
    fat_g: 10.5,
    sat_fat_g: 2.2,
    sodium_mg: 850,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.teacherkim.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-teacherkim-keto-creamcheese-220',
    channel: 'fr',
    brand: '바르다김선생',
    name: '키토 크림치즈 호두 김밥 220g',
    category: '도시락',
    price_krw: 6500,
    serving_g: 220,
    kcal: 360,
    protein_g: 18.0,
    carb_g: 12.0,
    sugar_g: 3.5,
    fat_g: 26.5,
    sat_fat_g: 9.5,
    sodium_mg: 740,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '밥 대신 계란지단 가득 저탄수 키토 김밥',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.teacherkim.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-teacherkim-spicy-pork-gimbap-260',
    channel: 'fr',
    brand: '바르다김선생',
    name: '매운 제육쌈 김밥 260g',
    category: '도시락',
    price_krw: 5800,
    serving_g: 260,
    kcal: 435,
    protein_g: 18.5,
    carb_g: 62.0,
    sugar_g: 6.5,
    fat_g: 12.5,
    sat_fat_g: 3.2,
    sodium_mg: 980,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.teacherkim.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-cuchara-burrito-bowl-chicken-410',
    channel: 'fr',
    brand: '쿠차라',
    name: '부리또 볼 치킨 410g',
    category: '샐러드',
    price_krw: 8900,
    serving_g: 410,
    kcal: 580,
    protein_g: 36.0,
    carb_g: 68.0,
    sugar_g: 4.0,
    fat_g: 17.5,
    sat_fat_g: 4.5,
    sodium_mg: 890,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '그릴 치킨 현미보리밥 블랙빈 단백질 36g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://cuchara.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-cuchara-burrito-bowl-steak-410',
    channel: 'fr',
    brand: '쿠차라',
    name: '부리또 볼 스테이크 410g',
    category: '샐러드',
    price_krw: 10900,
    serving_g: 410,
    kcal: 595,
    protein_g: 34.0,
    carb_g: 68.0,
    sugar_g: 4.0,
    fat_g: 19.0,
    sat_fat_g: 5.5,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '그릴 비프 스테이크 볼 단백질 34g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://cuchara.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-cuchara-burrito-bowl-tofu-400',
    channel: 'fr',
    brand: '쿠차라',
    name: '부리또 볼 두부 400g',
    category: '샐러드',
    price_krw: 7900,
    serving_g: 400,
    kcal: 510,
    protein_g: 22.0,
    carb_g: 70.0,
    sugar_g: 4.0,
    fat_g: 14.5,
    sat_fat_g: 2.2,
    sodium_mg: 760,
    protein_source: 'Q4',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '쿠차라 특제 멕시칸 두부 볼',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://cuchara.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 8. 스타벅스 & 투썸플레이스 (7개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-starbucks-bbq-chicken-cheese-ciabatta-145',
    channel: 'fr',
    brand: '스타벅스',
    name: '바비큐 치킨 치즈 치아바타 145g',
    category: '샌드위치/버거',
    price_krw: 5800,
    serving_g: 145,
    kcal: 320,
    protein_g: 18.0,
    carb_g: 39.0,
    sugar_g: 6.0,
    fat_g: 10.0,
    sat_fat_g: 3.8,
    sodium_mg: 720,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '치킨과 베이컨 치즈 치아바타 단백질 18g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.starbucks.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-starbucks-ham-rucola-olive-sandwich-190',
    channel: 'fr',
    brand: '스타벅스',
    name: '햄 & 루꼴라 올리브 샌드위치 190g',
    category: '샌드위치/버거',
    price_krw: 6200,
    serving_g: 190,
    kcal: 374,
    protein_g: 17.0,
    carb_g: 42.0,
    sugar_g: 5.0,
    fat_g: 15.0,
    sat_fat_g: 6.0,
    sodium_mg: 815,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.starbucks.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-starbucks-english-muffin-sandwich-140',
    channel: 'fr',
    brand: '스타벅스',
    name: '브렉퍼스트 잉글리쉬 머핀 샌드위치 140g',
    category: '샌드위치/버거',
    price_krw: 4500,
    serving_g: 140,
    kcal: 313,
    protein_g: 16.0,
    carb_g: 28.0,
    sugar_g: 3.0,
    fat_g: 15.0,
    sat_fat_g: 5.0,
    sodium_mg: 678,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.starbucks.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-starbucks-chicken-bacon-wrap-175',
    channel: 'fr',
    brand: '스타벅스',
    name: '치킨 베이컨 랩 175g',
    category: '샌드위치/버거',
    price_krw: 6500,
    serving_g: 175,
    kcal: 385,
    protein_g: 18.0,
    carb_g: 41.0,
    sugar_g: 5.0,
    fat_g: 16.0,
    sat_fat_g: 4.8,
    sodium_mg: 760,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.starbucks.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-twosome-mexican-panini-195',
    channel: 'fr',
    brand: '투썸플레이스',
    name: '멕시칸 파니니 195g',
    category: '샌드위치/버거',
    price_krw: 6900,
    serving_g: 195,
    kcal: 435,
    protein_g: 21.0,
    carb_g: 46.0,
    sugar_g: 5.0,
    fat_g: 18.0,
    sat_fat_g: 6.5,
    sodium_mg: 890,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '매콤한 치킨과 할라피뇨 치즈 파니니',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.twosome.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-twosome-grilled-chicken-salad-220',
    channel: 'fr',
    brand: '투썸플레이스',
    name: '그릴드 치킨 샐러드 220g',
    category: '샐러드',
    price_krw: 7800,
    serving_g: 220,
    kcal: 265,
    protein_g: 23.0,
    carb_g: 15.0,
    sugar_g: 6.0,
    fat_g: 12.0,
    sat_fat_g: 2.8,
    sodium_mg: 540,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '신선한 채소와 닭가슴살 단백질 23g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.twosome.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-twosome-pesto-ham-cheese-panini-190',
    channel: 'fr',
    brand: '투썸플레이스',
    name: '페스토 햄치즈 파니니 190g',
    category: '샌드위치/버거',
    price_krw: 6700,
    serving_g: 190,
    kcal: 420,
    protein_g: 18.5,
    carb_g: 44.0,
    sugar_g: 4.5,
    fat_g: 18.0,
    sat_fat_g: 6.0,
    sodium_mg: 840,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.twosome.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  }
];

function main() {
  const seedPath = path.join(rootDir, 'data', 'seed.json');
  const existingSeed = JSON.parse(fs.readFileSync(seedPath, 'utf-8'));
  const existingIdSet = new Set(existingSeed.map(x => x.menu_id));

  console.log(`기존 DB 품목 수: ${existingSeed.length}개`);
  console.log(`신규 외식 프랜차이즈 추가 대상: ${newFranchiseItems.length}개`);

  // QA 검증
  let failCount = 0;
  let warnCount = 0;
  for (const item of newFranchiseItems) {
    const qa = validateMenuQA(item, existingIdSet);
    if (!qa.valid) {
      console.error(`❌ [QA 에러] ${item.name}:`, qa.errors);
      failCount++;
    }
    if (qa.warnings.length > 0) {
      console.warn(`⚠️ [QA 경고] ${item.name}:`, qa.warnings);
      warnCount++;
    }
    existingIdSet.add(item.menu_id);
  }

  if (failCount > 0) {
    console.error(`💥 QA 에러 ${failCount}건 발생으로 중단합니다.`);
    process.exit(1);
  }

  console.log(`✅ 신규 ${newFranchiseItems.length}개 외식 품목 R1~R5 QA 통과 완료 (경고: ${warnCount}건)`);

  // 병합
  const merged = [...existingSeed, ...newFranchiseItems];
  fs.writeFileSync(seedPath, JSON.stringify(merged, null, 2), 'utf-8');
  console.log(`💾 data/seed.json 업데이트 완료! (총 ${merged.length}개)`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
