// scripts/add_cvs_batch4.js
// 편의점 핵심 카테고리(라면, 아이스크림, 과자/스낵, 도시락, 간편식/핫바 등) 85개 전면 발굴 및 추가
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { validateMenuQA } from '../js/qa.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

export const cvsBatch4Items = [
  // ─────────────────────────────────────────────────────────────
  // 1. 라면 / 컵라면 / 건면 (18개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'cvs-ottogi-cupnoodle-spicy-38',
    channel: 'cvs',
    brand: '오뚜기',
    name: '오뚜기 컵누들 매콤한맛 37.8g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 38,
    kcal: 120,
    protein_g: 3.0,
    carb_g: 27.0,
    sugar_g: 4.0,
    fat_g: 0.5,
    sat_fat_g: 0.2,
    sodium_mg: 890,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801045570114',
    source_type: 'T1',
    source_url: 'https://www.ottogi.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-ottogi-cupnoodle-udon-38',
    channel: 'cvs',
    brand: '오뚜기',
    name: '오뚜기 컵누들 우동맛 38.1g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 38,
    kcal: 120,
    protein_g: 3.0,
    carb_g: 26.0,
    sugar_g: 3.0,
    fat_g: 0.5,
    sat_fat_g: 0.1,
    sodium_mg: 870,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801045570213',
    source_type: 'T1',
    source_url: 'https://www.ottogi.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-ottogi-cupnoodle-jjimdak-46',
    channel: 'cvs',
    brand: '오뚜기',
    name: '오뚜기 컵누들 매콤찜닭맛 45.5g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 46,
    kcal: 150,
    protein_g: 3.0,
    carb_g: 33.0,
    sugar_g: 7.0,
    fat_g: 1.0,
    sat_fat_g: 0.3,
    sodium_mg: 640,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801045570312',
    source_type: 'T1',
    source_url: 'https://www.ottogi.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-ottogi-cupnoodle-jjajang-47',
    channel: 'cvs',
    brand: '오뚜기',
    name: '오뚜기 컵누들 짜장맛 46.5g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 47,
    kcal: 170,
    protein_g: 4.0,
    carb_g: 34.0,
    sugar_g: 6.0,
    fat_g: 2.0,
    sat_fat_g: 0.5,
    sodium_mg: 580,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801045570411',
    source_type: 'T1',
    source_url: 'https://www.ottogi.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-ottogi-cupnoodle-maratang-45',
    channel: 'cvs',
    brand: '오뚜기',
    name: '오뚜기 컵누들 마라탕맛 44.7g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 45,
    kcal: 150,
    protein_g: 3.0,
    carb_g: 26.0,
    sugar_g: 4.0,
    fat_g: 4.0,
    sat_fat_g: 1.2,
    sodium_mg: 820,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801045570510',
    source_type: 'T1',
    source_url: 'https://www.ottogi.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-ottogi-cupnoodle-pho-47',
    channel: 'cvs',
    brand: '오뚜기',
    name: '오뚜기 컵누들 베트남쌀국수 47g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 47,
    kcal: 140,
    protein_g: 3.0,
    carb_g: 32.0,
    sugar_g: 3.0,
    fat_g: 0.5,
    sat_fat_g: 0.1,
    sodium_mg: 850,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801045570619',
    source_type: 'T1',
    source_url: 'https://www.ottogi.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-nongshim-shin-geonmyeon-97',
    channel: 'cvs',
    brand: '농심',
    name: '농심 신라면 건면 97g',
    category: '라면/면류',
    price_krw: 1500,
    serving_g: 97,
    kcal: 350,
    protein_g: 10.0,
    carb_g: 68.0,
    sugar_g: 4.0,
    fat_g: 3.6,
    sat_fat_g: 1.2,
    sodium_mg: 1790,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '튀기지 않아 가벼운 논프라잉 건면',
    barcode: '8801043051776',
    source_type: 'T1',
    source_url: 'https://brand.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-nongshim-shin-bowl-114',
    channel: 'cvs',
    brand: '농심',
    name: '농심 신라면 큰사발면 114g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 114,
    kcal: 500,
    protein_g: 10.0,
    carb_g: 76.0,
    sugar_g: 5.0,
    fat_g: 17.0,
    sat_fat_g: 9.0,
    sodium_mg: 1690,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043003010',
    source_type: 'T1',
    source_url: 'https://brand.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-nongshim-shin-toomba-bowl-113',
    channel: 'cvs',
    brand: '농심',
    name: '농심 신라면 툼바 큰사발면 113g',
    category: '라면/면류',
    price_krw: 1900,
    serving_g: 113,
    kcal: 500,
    protein_g: 9.0,
    carb_g: 73.0,
    sugar_g: 8.0,
    fat_g: 19.0,
    sat_fat_g: 9.0,
    sodium_mg: 1390,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043065018',
    source_type: 'T1',
    source_url: 'https://brand.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-samyang-buldak-cup-105',
    channel: 'cvs',
    brand: '삼양식품',
    name: '삼양 불닭볶음면 큰컵 105g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 105,
    kcal: 425,
    protein_g: 9.0,
    carb_g: 63.0,
    sugar_g: 8.0,
    fat_g: 15.0,
    sat_fat_g: 8.0,
    sodium_mg: 950,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801073210419',
    source_type: 'T1',
    source_url: 'https://www.samyangfoods.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-samyang-carbo-buldak-cup-105',
    channel: 'cvs',
    brand: '삼양식품',
    name: '삼양 까르보불닭볶음면 큰컵 105g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 105,
    kcal: 470,
    protein_g: 8.0,
    carb_g: 65.0,
    sugar_g: 8.0,
    fat_g: 20.0,
    sat_fat_g: 10.0,
    sodium_mg: 1160,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801073211515',
    source_type: 'T1',
    source_url: 'https://www.samyangfoods.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-samyang-rose-buldak-cup-105',
    channel: 'cvs',
    brand: '삼양식품',
    name: '삼양 로제불닭볶음면 큰컵 105g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 105,
    kcal: 435,
    protein_g: 8.0,
    carb_g: 67.0,
    sugar_g: 7.0,
    fat_g: 15.0,
    sat_fat_g: 8.0,
    sodium_mg: 1140,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801073212819',
    source_type: 'T1',
    source_url: 'https://www.samyangfoods.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-nongshim-yukgaejang-bowl-86',
    channel: 'cvs',
    brand: '농심',
    name: '농심 육개장 사발면 86g',
    category: '라면/면류',
    price_krw: 1150,
    serving_g: 86,
    kcal: 375,
    protein_g: 7.0,
    carb_g: 53.0,
    sugar_g: 4.0,
    fat_g: 15.0,
    sat_fat_g: 8.0,
    sodium_mg: 1590,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043003416',
    source_type: 'T1',
    source_url: 'https://brand.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-nongshim-fried-udon-bowl-111',
    channel: 'cvs',
    brand: '농심',
    name: '농심 튀김우동 큰사발면 111g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 111,
    kcal: 495,
    protein_g: 8.0,
    carb_g: 75.0,
    sugar_g: 6.0,
    fat_g: 18.0,
    sat_fat_g: 9.0,
    sodium_mg: 1610,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043003515',
    source_type: 'T1',
    source_url: 'https://brand.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-nongshim-chapagetti-bowl-123',
    channel: 'cvs',
    brand: '농심',
    name: '농심 짜파게티 큰사발면 123g',
    category: '라면/면류',
    price_krw: 1800,
    serving_g: 123,
    kcal: 560,
    protein_g: 9.0,
    carb_g: 85.0,
    sugar_g: 6.0,
    fat_g: 20.0,
    sat_fat_g: 9.0,
    sodium_mg: 1180,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043003614',
    source_type: 'T1',
    source_url: 'https://brand.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-ottogi-jin-spicy-cup-110',
    channel: 'cvs',
    brand: '오뚜기',
    name: '오뚜기 진라면 매운맛 큰컵 110g',
    category: '라면/면류',
    price_krw: 1500,
    serving_g: 110,
    kcal: 500,
    protein_g: 10.0,
    carb_g: 73.0,
    sugar_g: 4.0,
    fat_g: 18.0,
    sat_fat_g: 8.0,
    sodium_mg: 1690,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801045520119',
    source_type: 'T1',
    source_url: 'https://www.ottogi.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-paldo-bibimmyeon-cup-115',
    channel: 'cvs',
    brand: '팔도',
    name: '팔도 비빔면 컵 115g',
    category: '라면/면류',
    price_krw: 1600,
    serving_g: 115,
    kcal: 465,
    protein_g: 8.0,
    carb_g: 71.0,
    sugar_g: 13.0,
    fat_g: 17.0,
    sat_fat_g: 8.0,
    sodium_mg: 1190,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801128503817',
    source_type: 'T1',
    source_url: 'https://www.paldofood.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-harim-themisik-artisan-ramen-cup-112',
    channel: 'cvs',
    brand: '하림',
    name: '하림 The미식 장인라면 얼큰한맛 컵 112g',
    category: '라면/면류',
    price_krw: 2800,
    serving_g: 112,
    kcal: 385,
    protein_g: 11.0,
    carb_g: 74.0,
    sugar_g: 4.0,
    fat_g: 5.0,
    sat_fat_g: 1.5,
    sodium_mg: 1780,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '사골 육수와 제트드라이 공법 건면',
    barcode: '8801104910219',
    source_type: 'T1',
    source_url: 'https://www.harim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 2. 아이스크림 (저당 / 고단백 / 편의점 대표 14개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'cvs-lalasweet-vanilla-chocobar-85',
    channel: 'cvs',
    brand: '라라스윗',
    name: '라라스윗 바닐라 초코바 90mL',
    category: '아이스크림',
    price_krw: 3300,
    serving_g: 85,
    kcal: 165,
    protein_g: 4.0,
    carb_g: 15.0,
    sugar_g: 2.0,
    fat_g: 11.0,
    sat_fat_g: 8.0,
    sodium_mg: 55,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '당류 2g 저당 초코바',
    barcode: '8809623130118',
    source_type: 'T1',
    source_url: 'https://lalasweet.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-lalasweet-chocolate-chocobar-85',
    channel: 'cvs',
    brand: '라라스윗',
    name: '라라스윗 초콜릿 초코바 90mL',
    category: '아이스크림',
    price_krw: 3300,
    serving_g: 85,
    kcal: 160,
    protein_g: 4.0,
    carb_g: 14.0,
    sugar_g: 2.0,
    fat_g: 11.0,
    sat_fat_g: 8.0,
    sodium_mg: 50,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '당류 2g 저당 초콜릿바',
    barcode: '8809623130125',
    source_type: 'T1',
    source_url: 'https://lalasweet.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-lalasweet-malcha-chocobar-85',
    channel: 'cvs',
    brand: '라라스윗',
    name: '라라스윗 말차 초코바 90mL',
    category: '아이스크림',
    price_krw: 3300,
    serving_g: 85,
    kcal: 165,
    protein_g: 4.0,
    carb_g: 15.0,
    sugar_g: 2.0,
    fat_g: 11.0,
    sat_fat_g: 8.0,
    sodium_mg: 55,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '제주 말차 저당 초코바',
    barcode: '8809623130132',
    source_type: 'T1',
    source_url: 'https://lalasweet.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-lalasweet-vanilla-monaka-85',
    channel: 'cvs',
    brand: '라라스윗',
    name: '라라스윗 바닐라 모나카 140mL',
    category: '아이스크림',
    price_krw: 3000,
    serving_g: 85,
    kcal: 125,
    protein_g: 5.0,
    carb_g: 20.0,
    sugar_g: 4.0,
    fat_g: 3.5,
    sat_fat_g: 2.2,
    sodium_mg: 70,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '125kcal 저칼로리 생우유 모나카',
    barcode: '8809623130217',
    source_type: 'T1',
    source_url: 'https://lalasweet.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-lalasweet-corn-monaka-85',
    channel: 'cvs',
    brand: '라라스윗',
    name: '라라스윗 옥수수 모나카 140mL',
    category: '아이스크림',
    price_krw: 3000,
    serving_g: 85,
    kcal: 135,
    protein_g: 5.0,
    carb_g: 22.0,
    sugar_g: 4.0,
    fat_g: 3.8,
    sat_fat_g: 2.3,
    sodium_mg: 75,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '135kcal 고소한 옥수수 모나카',
    barcode: '8809623130224',
    source_type: 'T1',
    source_url: 'https://lalasweet.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-lalasweet-chocolate-pint-270',
    channel: 'cvs',
    brand: '라라스윗',
    name: '라라스윗 초콜릿 파인트 474mL',
    category: '아이스크림',
    price_krw: 8900,
    serving_g: 270,
    kcal: 280,
    protein_g: 14.0,
    carb_g: 50.0,
    sugar_g: 8.0,
    fat_g: 7.0,
    sat_fat_g: 4.2,
    sodium_mg: 140,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '한 통 다 먹어도 280kcal 단백질 14g',
    barcode: '8809623130019',
    source_type: 'T1',
    source_url: 'https://lalasweet.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-skinnypig-double-choco-bar-80',
    channel: 'cvs',
    brand: '스키니피그',
    name: '스키니피그 더블초코 아이스크림바 90mL',
    category: '아이스크림',
    price_krw: 3200,
    serving_g: 80,
    kcal: 155,
    protein_g: 4.0,
    carb_g: 15.0,
    sugar_g: 2.5,
    fat_g: 10.0,
    sat_fat_g: 7.0,
    sodium_mg: 60,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '저당 저칼로리 초코 코팅바',
    barcode: '8809748950110',
    source_type: 'T1',
    source_url: 'https://skinnypig.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-skinnypig-vanilla-monaka-85',
    channel: 'cvs',
    brand: '스키니피그',
    name: '스키니피그 바닐라 모나카 140mL',
    category: '아이스크림',
    price_krw: 3000,
    serving_g: 85,
    kcal: 130,
    protein_g: 4.0,
    carb_g: 21.0,
    sugar_g: 3.0,
    fat_g: 3.5,
    sat_fat_g: 2.1,
    sodium_mg: 65,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '부담 없는 130kcal 샌드 모나카',
    barcode: '8809748950219',
    source_type: 'T1',
    source_url: 'https://skinnypig.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-lotte-zero-milk-monaka-85',
    channel: 'cvs',
    brand: '롯데',
    name: '롯데 제로 밀크 모나카 140mL',
    category: '아이스크림',
    price_krw: 2500,
    serving_g: 85,
    kcal: 150,
    protein_g: 4.0,
    carb_g: 23.0,
    sugar_g: 0.0,
    fat_g: 5.0,
    sat_fat_g: 3.2,
    sodium_mg: 80,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '설탕 무첨가 ZERO 모나카',
    barcode: '8801062886014',
    source_type: 'T1',
    source_url: 'https://www.lottefood.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-lotte-zero-chocobar-80',
    channel: 'cvs',
    brand: '롯데',
    name: '롯데 제로 밀크 초콜릿 바 90mL',
    category: '아이스크림',
    price_krw: 2500,
    serving_g: 80,
    kcal: 155,
    protein_g: 3.0,
    carb_g: 16.0,
    sugar_g: 0.0,
    fat_g: 10.5,
    sat_fat_g: 7.0,
    sodium_mg: 55,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '설탕 무첨가 ZERO 초콜릿바',
    barcode: '8801062886021',
    source_type: 'T1',
    source_url: 'https://www.lottefood.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-binggrae-together-mini-140',
    channel: 'cvs',
    brand: '빙그레',
    name: '빙그레 투게더 미니어처 바닐라 250mL',
    category: '아이스크림',
    price_krw: 3500,
    serving_g: 140,
    kcal: 280,
    protein_g: 5.0,
    carb_g: 30.0,
    sugar_g: 24.0,
    fat_g: 16.0,
    sat_fat_g: 10.0,
    sodium_mg: 90,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801104230119',
    source_type: 'T1',
    source_url: 'https://www.bing.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-binggrae-merona-75',
    channel: 'cvs',
    brand: '빙그레',
    name: '빙그레 메로나 75mL',
    category: '아이스크림',
    price_krw: 1200,
    serving_g: 75,
    kcal: 120,
    protein_g: 1.0,
    carb_g: 19.0,
    sugar_g: 15.0,
    fat_g: 4.5,
    sat_fat_g: 3.0,
    sodium_mg: 45,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801104230218',
    source_type: 'T1',
    source_url: 'https://www.bing.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-binggrae-samanko-120',
    channel: 'cvs',
    brand: '빙그레',
    name: '빙그레 참붕어싸만코 150mL',
    category: '아이스크림',
    price_krw: 2000,
    serving_g: 120,
    kcal: 210,
    protein_g: 3.5,
    carb_g: 36.0,
    sugar_g: 22.0,
    fat_g: 6.0,
    sat_fat_g: 3.8,
    sodium_mg: 85,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801104230317',
    source_type: 'T1',
    source_url: 'https://www.bing.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-haitai-bravo-cone-140',
    channel: 'cvs',
    brand: '해태',
    name: '해태 부라보콘 바닐라 140mL',
    category: '아이스크림',
    price_krw: 2000,
    serving_g: 140,
    kcal: 240,
    protein_g: 4.0,
    carb_g: 34.0,
    sugar_g: 21.0,
    fat_g: 10.0,
    sat_fat_g: 6.0,
    sodium_mg: 95,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801019201112',
    source_type: 'T1',
    source_url: 'https://www.haitai.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 3. 과자 / 스낵 / 디저트 (20개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'cvs-orion-dryou-chip-chili-60',
    channel: 'cvs',
    brand: '오리온',
    name: '오리온 닥터유 단백질칩 칠리살사맛 60g',
    category: '과자/바',
    price_krw: 2000,
    serving_g: 60,
    kcal: 260,
    protein_g: 12.0,
    carb_g: 36.0,
    sugar_g: 3.0,
    fat_g: 8.0,
    sat_fat_g: 3.2,
    sodium_mg: 420,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '달걀 2개 분량 단백질 12g 바삭한 단백질칩',
    barcode: '8801117180111',
    source_type: 'T1',
    source_url: 'https://www.orionworld.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-orion-dryou-chip-butter-60',
    channel: 'cvs',
    brand: '오리온',
    name: '오리온 닥터유 단백질칩 버터솔트맛 60g',
    category: '과자/바',
    price_krw: 2000,
    serving_g: 60,
    kcal: 260,
    protein_g: 12.0,
    carb_g: 36.0,
    sugar_g: 3.0,
    fat_g: 8.0,
    sat_fat_g: 3.2,
    sodium_mg: 390,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '달걀 2개 분량 단백질 12g',
    barcode: '8801117180128',
    source_type: 'T1',
    source_url: 'https://www.orionworld.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-orion-dryou-ball-48',
    channel: 'cvs',
    brand: '오리온',
    name: '오리온 닥터유 단백질볼 48g',
    category: '과자/바',
    price_krw: 1800,
    serving_g: 48,
    kcal: 248,
    protein_g: 12.0,
    carb_g: 22.0,
    sugar_g: 13.0,
    fat_g: 12.0,
    sat_fat_g: 7.0,
    sodium_mg: 75,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '달걀 2개 분량 단백질 12g 초코볼',
    barcode: '8801117180135',
    source_type: 'T1',
    source_url: 'https://www.orionworld.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-orion-kkobuk-chocochurros-80',
    channel: 'cvs',
    brand: '오리온',
    name: '오리온 꼬북칩 초코츄러스맛 80g',
    category: '과자/바',
    price_krw: 1700,
    serving_g: 80,
    kcal: 428,
    protein_g: 5.0,
    carb_g: 52.0,
    sugar_g: 24.0,
    fat_g: 22.0,
    sat_fat_g: 12.0,
    sodium_mg: 210,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801117180142',
    source_type: 'T1',
    source_url: 'https://www.orionworld.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-orion-pocachip-original-66',
    channel: 'cvs',
    brand: '오리온',
    name: '오리온 포카칩 오리지널 66g',
    category: '과자/바',
    price_krw: 1700,
    serving_g: 66,
    kcal: 377,
    protein_g: 4.0,
    carb_g: 34.0,
    sugar_g: 0.6,
    fat_g: 25.0,
    sat_fat_g: 9.0,
    sodium_mg: 280,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801117180159',
    source_type: 'T1',
    source_url: 'https://www.orionworld.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-orion-sun-hot-spicy-64',
    channel: 'cvs',
    brand: '오리온',
    name: '오리온 태양의맛 썬 핫스파이시 64g',
    category: '과자/바',
    price_krw: 1700,
    serving_g: 64,
    kcal: 332,
    protein_g: 4.0,
    carb_g: 42.0,
    sugar_g: 6.0,
    fat_g: 16.0,
    sat_fat_g: 6.0,
    sodium_mg: 290,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801117180166',
    source_type: 'T1',
    source_url: 'https://www.orionworld.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-nongshim-meoktaekkang-60',
    channel: 'cvs',
    brand: '농심',
    name: '농심 먹태깡 청양마요맛 60g',
    category: '과자/바',
    price_krw: 1700,
    serving_g: 60,
    kcal: 280,
    protein_g: 6.0,
    carb_g: 42.0,
    sugar_g: 12.0,
    fat_g: 10.0,
    sat_fat_g: 3.5,
    sodium_mg: 450,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043064011',
    source_type: 'T1',
    source_url: 'https://brand.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-nongshim-saewookkang-90',
    channel: 'cvs',
    brand: '농심',
    name: '농심 새우깡 90g',
    category: '과자/바',
    price_krw: 1500,
    serving_g: 90,
    kcal: 465,
    protein_g: 6.0,
    carb_g: 60.0,
    sugar_g: 6.0,
    fat_g: 22.0,
    sat_fat_g: 8.0,
    sodium_mg: 610,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043014016',
    source_type: 'T1',
    source_url: 'https://brand.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-nongshim-maeun-saewookkang-90',
    channel: 'cvs',
    brand: '농심',
    name: '농심 매운 새우깡 90g',
    category: '과자/바',
    price_krw: 1500,
    serving_g: 90,
    kcal: 465,
    protein_g: 6.0,
    carb_g: 60.0,
    sugar_g: 7.0,
    fat_g: 22.0,
    sat_fat_g: 8.0,
    sodium_mg: 650,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043014023',
    source_type: 'T1',
    source_url: 'https://brand.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-nongshim-potato-chip-original-60',
    channel: 'cvs',
    brand: '농심',
    name: '농심 포테토칩 오리지널 60g',
    category: '과자/바',
    price_krw: 1700,
    serving_g: 60,
    kcal: 350,
    protein_g: 4.0,
    carb_g: 31.0,
    sugar_g: 0.5,
    fat_g: 23.0,
    sat_fat_g: 8.0,
    sodium_mg: 250,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801043014030',
    source_type: 'T1',
    source_url: 'https://brand.nongshim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-lotte-zero-cacao-cake-56',
    channel: 'cvs',
    brand: '롯데',
    name: '롯데 제로 카카오 케이크 56g (2개입)',
    category: '과자/바',
    price_krw: 2000,
    serving_g: 56,
    kcal: 180,
    protein_g: 4.0,
    carb_g: 24.0,
    sugar_g: 0.0,
    fat_g: 9.0,
    sat_fat_g: 5.0,
    sodium_mg: 120,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '설탕 무첨가 ZERO 초콜릿 케이크',
    barcode: '8801062886038',
    source_type: 'T1',
    source_url: 'https://www.lottefood.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-lotte-zero-crunch-chocoball-34',
    channel: 'cvs',
    brand: '롯데',
    name: '롯데 제로 크런치 초코볼 34g',
    category: '과자/바',
    price_krw: 1700,
    serving_g: 34,
    kcal: 140,
    protein_g: 3.0,
    carb_g: 17.0,
    sugar_g: 0.0,
    fat_g: 8.0,
    sat_fat_g: 5.0,
    sodium_mg: 45,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '설탕 무첨가 크런치 초코볼',
    barcode: '8801062886045',
    source_type: 'T1',
    source_url: 'https://www.lottefood.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-haitai-honey-butter-chip-60',
    channel: 'cvs',
    brand: '해태',
    name: '해태 허니버터칩 60g',
    category: '과자/바',
    price_krw: 1700,
    serving_g: 60,
    kcal: 345,
    protein_g: 3.0,
    carb_g: 33.0,
    sugar_g: 2.0,
    fat_g: 22.0,
    sat_fat_g: 8.0,
    sodium_mg: 270,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801019606443',
    source_type: 'T1',
    source_url: 'https://www.haitai.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-haitai-baked-onion-70',
    channel: 'cvs',
    brand: '해태',
    name: '해태 구운양파 70g',
    category: '과자/바',
    price_krw: 1700,
    serving_g: 70,
    kcal: 375,
    protein_g: 4.5,
    carb_g: 45.0,
    sugar_g: 4.0,
    fat_g: 20.0,
    sat_fat_g: 7.0,
    sodium_mg: 440,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801019606450',
    source_type: 'T1',
    source_url: 'https://www.haitai.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-crown-cornchip-70',
    channel: 'cvs',
    brand: '크라운',
    name: '크라운 C콘chip 옥수수 70g',
    category: '과자/바',
    price_krw: 1700,
    serving_g: 70,
    kcal: 360,
    protein_g: 4.0,
    carb_g: 46.0,
    sugar_g: 3.0,
    fat_g: 18.0,
    sat_fat_g: 6.0,
    sodium_mg: 280,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801111111202',
    source_type: 'T1',
    source_url: 'https://www.crown.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-delight-garlic-butter-bagelchip-60',
    channel: 'cvs',
    brand: '딜라이트프로젝트',
    name: '딜라이트 프로젝트 갈릭버터 베이글칩 60g',
    category: '과자/바',
    price_krw: 2700,
    serving_g: 60,
    kcal: 260,
    protein_g: 6.0,
    carb_g: 45.0,
    sugar_g: 14.0,
    fat_g: 6.0,
    sat_fat_g: 2.5,
    sodium_mg: 340,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809653240115',
    source_type: 'T1',
    source_url: 'https://www.oliveyoung.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-delight-protein-bagelchip-55',
    channel: 'cvs',
    brand: '딜라이트프로젝트',
    name: '딜라이트 프로젝트 단백질 베이글칩 55g',
    category: '과자/바',
    price_krw: 2900,
    serving_g: 55,
    kcal: 245,
    protein_g: 12.0,
    carb_g: 36.0,
    sugar_g: 10.0,
    fat_g: 5.5,
    sat_fat_g: 2.2,
    sodium_mg: 310,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '단백질 12g 함유 고단백 베이글칩',
    barcode: '8809653240122',
    source_type: 'T1',
    source_url: 'https://www.oliveyoung.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-labnosh-cookiebar-black-40',
    channel: 'cvs',
    brand: '랩노쉬',
    name: '랩노쉬 프로틴 쿠키바 블랙쿠키 40g',
    category: '과자/바',
    price_krw: 2200,
    serving_g: 40,
    kcal: 160,
    protein_g: 8.0,
    carb_g: 20.0,
    sugar_g: 3.0,
    fat_g: 6.0,
    sat_fat_g: 3.5,
    sodium_mg: 120,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '단백질 8g 저당 쿠키바',
    barcode: '8809548760223',
    source_type: 'T1',
    source_url: 'https://labnosh.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-mymil-protein-bar-nuts-40',
    channel: 'cvs',
    brand: '마이밀',
    name: '마이밀 프로틴 바 견과류 40g',
    category: '과자/바',
    price_krw: 2000,
    serving_g: 40,
    kcal: 165,
    protein_g: 9.0,
    carb_g: 18.0,
    sugar_g: 6.0,
    fat_g: 6.5,
    sat_fat_g: 2.5,
    sodium_mg: 90,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '동식물성 균형 단백질 9g',
    barcode: '8801155734211',
    source_type: 'T1',
    source_url: 'https://www.daesangwellife.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cheongjungone-chew-pea-35',
    channel: 'cvs',
    brand: '청정원',
    name: '청정원 츄앤크리스피 완두 35g',
    category: '과자/바',
    price_krw: 2500,
    serving_g: 35,
    kcal: 145,
    protein_g: 6.0,
    carb_g: 21.0,
    sugar_g: 2.0,
    fat_g: 4.5,
    sat_fat_g: 1.5,
    sodium_mg: 150,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '완두콩 원물 그대로 바삭한 스낵',
    barcode: '8801052731119',
    source_type: 'T1',
    source_url: 'https://www.daesang.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 4. 편의점 대표 도시락 / 컵밥 (15개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'cvs-gs25-hyeja-7side-480',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 혜자로운 집밥 7첩반상 도시락 480g',
    category: '도시락',
    price_krw: 5500,
    serving_g: 480,
    kcal: 750,
    protein_g: 31.0,
    carb_g: 105.0,
    sugar_g: 11.0,
    fat_g: 23.0,
    sat_fat_g: 6.5,
    sodium_mg: 1390,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801070001010',
    source_type: 'T1',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-hyeja-tongtong-soya-450',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 혜자로운 집밥 통통쏘야 도시락 450g',
    category: '도시락',
    price_krw: 5000,
    serving_g: 450,
    kcal: 690,
    protein_g: 26.0,
    carb_g: 96.0,
    sugar_g: 12.0,
    fat_g: 22.0,
    sat_fat_g: 7.0,
    sodium_mg: 1320,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801070001027',
    source_type: 'T1',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-hyeja-egghambak-460',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 혜자로운 집밥 에그함박 도시락 460g',
    category: '도시락',
    price_krw: 5500,
    serving_g: 460,
    kcal: 780,
    protein_g: 33.0,
    carb_g: 92.0,
    sugar_g: 10.0,
    fat_g: 31.0,
    sat_fat_g: 9.0,
    sodium_mg: 1420,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801070001034',
    source_type: 'T1',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-hyeja-chicken-sausage-410',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 혜자로운 집밥 닭가슴살소시지 도시락 410g',
    category: '도시락',
    price_krw: 4900,
    serving_g: 410,
    kcal: 550,
    protein_g: 30.0,
    carb_g: 78.0,
    sugar_g: 6.0,
    fat_g: 13.0,
    sat_fat_g: 3.5,
    sodium_mg: 1050,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '단백질 30g 든든한 한끼',
    barcode: '8801070001041',
    source_type: 'T1',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-baek-hanpan-460',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 백종원 한판 도시락 460g',
    category: '도시락',
    price_krw: 4500,
    serving_g: 460,
    kcal: 720,
    protein_g: 29.0,
    carb_g: 102.0,
    sugar_g: 9.0,
    fat_g: 22.0,
    sat_fat_g: 6.0,
    sodium_mg: 1350,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801055001011',
    source_type: 'T1',
    source_url: 'http://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-baek-spicy-bulgogi-440',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 백종원 매콤 불고기 도시락 440g',
    category: '도시락',
    price_krw: 4700,
    serving_g: 440,
    kcal: 710,
    protein_g: 28.0,
    carb_g: 98.0,
    sugar_g: 11.0,
    fat_g: 23.0,
    sat_fat_g: 6.5,
    sodium_mg: 1410,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801055001028',
    source_type: 'T1',
    source_url: 'http://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-baek-bassak-bulgogi-430',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 백종원 바싹 불고기 한판 430g',
    category: '도시락',
    price_krw: 4800,
    serving_g: 430,
    kcal: 680,
    protein_g: 27.0,
    carb_g: 95.0,
    sugar_g: 8.0,
    fat_g: 21.0,
    sat_fat_g: 5.5,
    sodium_mg: 1290,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801055001035',
    source_type: 'T1',
    source_url: 'http://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-baek-7side-hanpan-470',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 백종원 7첩 한판 도시락 470g',
    category: '도시락',
    price_krw: 5200,
    serving_g: 470,
    kcal: 760,
    protein_g: 32.0,
    carb_g: 104.0,
    sugar_g: 10.0,
    fat_g: 24.0,
    sat_fat_g: 7.0,
    sodium_mg: 1440,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801055001042',
    source_type: 'T1',
    source_url: 'http://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-baek-triple-tonkatsu-490',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 백종원 트리플 돈까스 도시락 490g',
    category: '도시락',
    price_krw: 5300,
    serving_g: 490,
    kcal: 840,
    protein_g: 31.0,
    carb_g: 110.0,
    sugar_g: 12.0,
    fat_g: 31.0,
    sat_fat_g: 8.5,
    sodium_mg: 1520,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801055001059',
    source_type: 'T1',
    source_url: 'http://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-seven-matjangwoo-bibim-430',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '세븐일레븐 맛장우 전주비빔밥 도시락 430g',
    category: '도시락',
    price_krw: 4800,
    serving_g: 430,
    kcal: 620,
    protein_g: 22.0,
    carb_g: 98.0,
    sugar_g: 10.0,
    fat_g: 15.0,
    sat_fat_g: 3.5,
    sodium_mg: 1280,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801088001019',
    source_type: 'T1',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-seven-matjangwoo-spicy-jeyuk-450',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '세븐일레븐 맛장우 매콤제육 도시락 450g',
    category: '도시락',
    price_krw: 4900,
    serving_g: 450,
    kcal: 695,
    protein_g: 28.0,
    carb_g: 97.0,
    sugar_g: 11.0,
    fat_g: 21.0,
    sat_fat_g: 6.0,
    sodium_mg: 1360,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801088001026',
    source_type: 'T1',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-seven-matjangwoo-bulbaek-460',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '세븐일레븐 맛장우 든든한불백 도시락 460g',
    category: '도시락',
    price_krw: 5200,
    serving_g: 460,
    kcal: 710,
    protein_g: 29.0,
    carb_g: 99.0,
    sugar_g: 10.0,
    fat_g: 22.0,
    sat_fat_g: 6.2,
    sodium_mg: 1390,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801088001033',
    source_type: 'T1',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-emart24-bassak-sausage-440',
    channel: 'cvs',
    brand: '이마트24',
    name: '이마트24 바싹불고기&소시지 도시락 440g',
    category: '도시락',
    price_krw: 4800,
    serving_g: 440,
    kcal: 680,
    protein_g: 26.0,
    carb_g: 95.0,
    sugar_g: 9.0,
    fat_g: 21.0,
    sat_fat_g: 6.0,
    sodium_mg: 1340,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809568910118',
    source_type: 'T1',
    source_url: 'https://www.emart24.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-emart24-smoked-duck-390',
    channel: 'cvs',
    brand: '이마트24',
    name: '이마트24 훈제오리&채소 도시락 390g',
    category: '도시락',
    price_krw: 5300,
    serving_g: 390,
    kcal: 520,
    protein_g: 28.0,
    carb_g: 62.0,
    sugar_g: 5.0,
    fat_g: 17.0,
    sat_fat_g: 4.5,
    sodium_mg: 980,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '담백한 훈제오리 단백질 28g',
    barcode: '8809568910125',
    source_type: 'T1',
    source_url: 'https://www.emart24.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cj-cupban-tuna-mayo-247',
    channel: 'cvs',
    brand: 'CJ제일제당',
    name: 'CJ 햇반컵반 참치마요덮밥 247g',
    category: '도시락',
    price_krw: 3900,
    serving_g: 247,
    kcal: 380,
    protein_g: 10.0,
    carb_g: 58.0,
    sugar_g: 4.0,
    fat_g: 12.0,
    sat_fat_g: 2.5,
    sodium_mg: 720,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801007421115',
    source_type: 'T1',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 5. 삼각김밥 / 줄김밥 / 간편식 / 핫바 / 편의점 즉석치킨 (18개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'cvs-gs25-tuna-mayo-gimbap-240',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 참치마요 김밥 240g',
    category: '삼각김밥/주먹밥',
    price_krw: 2800,
    serving_g: 240,
    kcal: 370,
    protein_g: 11.0,
    carb_g: 56.0,
    sugar_g: 3.5,
    fat_g: 11.0,
    sat_fat_g: 2.2,
    sodium_mg: 890,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801070002017',
    source_type: 'T1',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-tong-sausage-gimbap-245',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 바삭통소시지 김밥 245g',
    category: '삼각김밥/주먹밥',
    price_krw: 3000,
    serving_g: 245,
    kcal: 410,
    protein_g: 13.0,
    carb_g: 55.0,
    sugar_g: 4.0,
    fat_g: 15.0,
    sat_fat_g: 4.5,
    sodium_mg: 990,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801070002024',
    source_type: 'T1',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-bigger-chicken-leg-170',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 더큰 닭다리 즉석조리 170g',
    category: '닭가슴살/육가공',
    price_krw: 2900,
    serving_g: 170,
    kcal: 320,
    protein_g: 24.0,
    carb_g: 14.0,
    sugar_g: 2.0,
    fat_g: 18.0,
    sat_fat_g: 4.5,
    sodium_mg: 780,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '갓 튀겨낸 단백질 24g 통닭다리',
    barcode: null,
    source_type: 'T1',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-crispy-tongdari-chicken-180',
    channel: 'cvs',
    brand: 'GS25',
    name: 'GS25 바삭통다리 치킨 180g',
    category: '닭가슴살/육가공',
    price_krw: 3100,
    serving_g: 180,
    kcal: 340,
    protein_g: 25.0,
    carb_g: 16.0,
    sugar_g: 2.0,
    fat_g: 19.0,
    sat_fat_g: 5.0,
    sodium_mg: 820,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '육즙 가득 단백질 25g',
    barcode: null,
    source_type: 'T1',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-tuna-mayo-samgak-110',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 참치마요 삼각김밥 110g',
    category: '삼각김밥/주먹밥',
    price_krw: 1200,
    serving_g: 110,
    kcal: 215,
    protein_g: 6.0,
    carb_g: 33.0,
    sugar_g: 1.5,
    fat_g: 6.5,
    sat_fat_g: 1.2,
    sodium_mg: 410,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801055002018',
    source_type: 'T1',
    source_url: 'http://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-jeonju-bibim-samgak-110',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 전주비빔 삼각김밥 110g',
    category: '삼각김밥/주먹밥',
    price_krw: 1200,
    serving_g: 110,
    kcal: 195,
    protein_g: 4.5,
    carb_g: 36.0,
    sugar_g: 2.0,
    fat_g: 3.8,
    sat_fat_g: 0.8,
    sodium_mg: 480,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801055002025',
    source_type: 'T1',
    source_url: 'http://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-baek-spicy-jeyuk-gimbap-235',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 백종원 매콤제육 김밥 235g',
    category: '삼각김밥/주먹밥',
    price_krw: 2900,
    serving_g: 235,
    kcal: 360,
    protein_g: 12.0,
    carb_g: 54.0,
    sugar_g: 4.0,
    fat_g: 10.5,
    sat_fat_g: 2.8,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801055002032',
    source_type: 'T1',
    source_url: 'http://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-giant-hotbar-spicy-100',
    channel: 'cvs',
    brand: 'CU',
    name: 'CU 자이언트 핫바 매콤한맛 100g',
    category: '닭가슴살/육가공',
    price_krw: 2200,
    serving_g: 100,
    kcal: 185,
    protein_g: 12.0,
    carb_g: 15.0,
    sugar_g: 3.0,
    fat_g: 8.5,
    sat_fat_g: 2.5,
    sodium_mg: 720,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801055002049',
    source_type: 'T1',
    source_url: 'http://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-seven-bigger-tuna-mayo-samgak-140',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '세븐일레븐 더커진 참치마요 삼각김밥 140g',
    category: '삼각김밥/주먹밥',
    price_krw: 1500,
    serving_g: 140,
    kcal: 260,
    protein_g: 7.0,
    carb_g: 43.0,
    sugar_g: 2.0,
    fat_g: 6.8,
    sat_fat_g: 1.5,
    sodium_mg: 520,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801088002016',
    source_type: 'T1',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-seven-roasted-chicken-leg-160',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '세븐일레븐 통닭다리구이 160g',
    category: '닭가슴살/육가공',
    price_krw: 3500,
    serving_g: 160,
    kcal: 280,
    protein_g: 25.0,
    carb_g: 6.0,
    sugar_g: 3.0,
    fat_g: 17.0,
    sat_fat_g: 4.2,
    sodium_mg: 760,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '오븐에 구워 기름 뺀 단백질 25g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cj-maxbon-cheese-55',
    channel: 'cvs',
    brand: 'CJ제일제당',
    name: 'CJ 맥스봉 치즈소시지 55g',
    category: '닭가슴살/육가공',
    price_krw: 1800,
    serving_g: 55,
    kcal: 95,
    protein_g: 6.0,
    carb_g: 8.0,
    sugar_g: 2.0,
    fat_g: 4.3,
    sat_fat_g: 1.8,
    sodium_mg: 380,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801007051114',
    source_type: 'T1',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cj-samho-odeng-bowl-360',
    channel: 'cvs',
    brand: 'CJ제일제당',
    name: 'CJ 삼호어묵 오뎅한그릇 360g',
    category: '기타',
    price_krw: 3200,
    serving_g: 360,
    kcal: 175,
    protein_g: 12.0,
    carb_g: 18.0,
    sugar_g: 5.0,
    fat_g: 6.0,
    sat_fat_g: 1.2,
    sodium_mg: 1650,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801007051121',
    source_type: 'T1',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-jinju-cheonhajangsa-original-50',
    channel: 'cvs',
    brand: '진주햄',
    name: '진주햄 천하장사 오리지널 50g',
    category: '닭가슴살/육가공',
    price_krw: 1500,
    serving_g: 50,
    kcal: 80,
    protein_g: 5.0,
    carb_g: 7.0,
    sugar_g: 1.5,
    fat_g: 3.5,
    sat_fat_g: 1.2,
    sodium_mg: 350,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801121010114',
    source_type: 'T1',
    source_url: 'http://www.jinju.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-sajo-charcoal-hotbar-80',
    channel: 'cvs',
    brand: '사조대림',
    name: '사조 대림선 숯불구이맛 핫바 80g',
    category: '닭가슴살/육가공',
    price_krw: 2000,
    serving_g: 80,
    kcal: 170,
    protein_g: 10.0,
    carb_g: 12.0,
    sugar_g: 3.0,
    fat_g: 9.0,
    sat_fat_g: 2.8,
    sodium_mg: 620,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801037041110',
    source_type: 'T1',
    source_url: 'https://www.sajo.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-sajo-wheeltouch-hotbar-80',
    channel: 'cvs',
    brand: '사조대림',
    name: '사조 대림선 휠터치 핫바 80g',
    category: '닭가슴살/육가공',
    price_krw: 2000,
    serving_g: 80,
    kcal: 175,
    protein_g: 10.0,
    carb_g: 11.0,
    sugar_g: 2.5,
    fat_g: 10.0,
    sat_fat_g: 3.2,
    sodium_mg: 640,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801037041127',
    source_type: 'T1',
    source_url: 'https://www.sajo.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-harim-chicken-hotbar-garlic-80',
    channel: 'cvs',
    brand: '하림',
    name: '하림 닭가슴살 핫바 갈릭 80g',
    category: '닭가슴살/육가공',
    price_krw: 2300,
    serving_g: 80,
    kcal: 115,
    protein_g: 14.0,
    carb_g: 4.0,
    sugar_g: 2.0,
    fat_g: 4.2,
    sat_fat_g: 1.2,
    sodium_mg: 480,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '국내산 닭가슴살 단백질 14g',
    barcode: '8801104910318',
    source_type: 'T1',
    source_url: 'https://www.harim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-harim-chicken-hotbar-smoked-80',
    channel: 'cvs',
    brand: '하림',
    name: '하림 닭가슴살 핫바 훈제 80g',
    category: '닭가슴살/육가공',
    price_krw: 2300,
    serving_g: 80,
    kcal: 110,
    protein_g: 14.0,
    carb_g: 3.5,
    sugar_g: 1.5,
    fat_g: 4.0,
    sat_fat_g: 1.1,
    sodium_mg: 460,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '참나무 훈제 닭가슴살 단백질 14g',
    barcode: '8801104910325',
    source_type: 'T1',
    source_url: 'https://www.harim.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-samlip-cheese-pangpang-hotdog-100',
    channel: 'cvs',
    brand: '삼립',
    name: '삼립 치즈팡팡 핫도그 100g',
    category: '샌드위치/버거',
    price_krw: 2200,
    serving_g: 100,
    kcal: 260,
    protein_g: 8.0,
    carb_g: 32.0,
    sugar_g: 6.0,
    fat_g: 11.0,
    sat_fat_g: 3.8,
    sodium_mg: 520,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068301115',
    source_type: 'T1',
    source_url: 'https://spcsamlip.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  }
];

// 실행 함수
function main() {
  const seedPath = path.join(rootDir, 'data', 'seed.json');
  const existingData = JSON.parse(fs.readFileSync(seedPath, 'utf-8'));
  const existingIds = new Set(existingData.map(d => d.menu_id));

  console.log(`기존 DB 품목 수: ${existingData.length}개`);
  console.log(`신규 편의점 4차 추가 대상: ${cvsBatch4Items.length}개`);

  let qaErrors = 0;
  let qaWarnings = 0;

  for (const item of cvsBatch4Items) {
    const qa = validateMenuQA(item, existingIds);
    if (!qa.valid) {
      console.error(`❌ [QA 오류] ${item.name} (${item.menu_id}):`, qa.errors);
      qaErrors++;
    }
    if (qa.warnings.length > 0) {
      console.warn(`⚠️ [QA 경고] ${item.name}:`, qa.warnings);
      qaWarnings++;
    }
  }

  if (qaErrors > 0) {
    console.error(`💥 총 ${qaErrors}건의 QA 오류가 발생하여 추가를 중단합니다.`);
    process.exit(1);
  }

  console.log(`✅ 신규 ${cvsBatch4Items.length}개 품목 R1~R5 QA 통과 완료 (경고: ${qaWarnings}건)`);

  const updatedData = [...existingData, ...cvsBatch4Items];
  fs.writeFileSync(seedPath, JSON.stringify(updatedData, null, 2), 'utf-8');
  console.log(`💾 data/seed.json 업데이트 완료! (총 ${updatedData.length}개)`);
}

main();
