// scripts/add_franchise_batch3.js
// 주요 외식 프랜차이즈 전 브랜드 결측 시그니처 메뉴 85개 전면 발굴 및 추가
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { validateMenuQA } from '../js/qa.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

export const batch3Items = [
  // ─────────────────────────────────────────────────────────────
  // 1. 써브웨이 (5개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-subway-italian-bmt-15cm-226',
    channel: 'fr',
    brand: '써브웨이',
    name: '이탈리안 비엠티 15cm',
    category: '샌드위치/버거',
    price_krw: 6900,
    serving_g: 226,
    kcal: 388,
    protein_g: 21.0,
    carb_g: 40.0,
    sugar_g: 7.9,
    fat_g: 16.0,
    sat_fat_g: 5.6,
    sodium_mg: 1064,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '페퍼로니 살라미 햄 써브웨이 전세계 1위',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-spicy-italian-15cm-218',
    channel: 'fr',
    brand: '써브웨이',
    name: '스파이시 이탈리안 15cm',
    category: '샌드위치/버거',
    price_krw: 6900,
    serving_g: 218,
    kcal: 464,
    protein_g: 19.3,
    carb_g: 39.0,
    sugar_g: 7.5,
    fat_g: 25.5,
    sat_fat_g: 9.2,
    sodium_mg: 1020,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-tuna-15cm-238',
    channel: 'fr',
    brand: '써브웨이',
    name: '참치 15cm',
    category: '샌드위치/버거',
    price_krw: 5800,
    serving_g: 238,
    kcal: 316,
    protein_g: 19.3,
    carb_g: 39.0,
    sugar_g: 7.5,
    fat_g: 9.0,
    sat_fat_g: 1.8,
    sodium_mg: 535,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-chicken-bacon-avocado-15cm-260',
    channel: 'fr',
    brand: '써브웨이',
    name: '치킨 베이컨 아보카도 15cm',
    category: '샌드위치/버거',
    price_krw: 8200,
    serving_g: 260,
    kcal: 355,
    protein_g: 25.5,
    carb_g: 41.0,
    sugar_g: 7.8,
    fat_g: 9.8,
    sat_fat_g: 2.8,
    sodium_mg: 790,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '담백한 닭가슴살과 아보카도 단백질 25.5g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-rotisserie-chicken-salad-300',
    channel: 'fr',
    brand: '써브웨이',
    name: '로티세리 바비큐 치킨 샐러드 300g',
    category: '샐러드',
    price_krw: 9300,
    serving_g: 300,
    kcal: 210,
    protein_g: 31.0,
    carb_g: 11.0,
    sugar_g: 6.5,
    fat_g: 4.8,
    sat_fat_g: 1.2,
    sodium_mg: 480,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '부드러운 바비큐 치킨 샐러드 단백질 31g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 2. 샐러디 (5개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-salady-caesar-chicken-salad-210',
    channel: 'fr',
    brand: '샐러디',
    name: '시저치킨 샐러디 210g',
    category: '샐러드',
    price_krw: 7400,
    serving_g: 210,
    kcal: 235,
    protein_g: 25.8,
    carb_g: 10.0,
    sugar_g: 3.5,
    fat_g: 10.2,
    sat_fat_g: 2.8,
    sodium_mg: 510,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '담백한 닭가슴살 샐러디 스테디셀러',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-salady-salmon-salad-230',
    channel: 'fr',
    brand: '샐러디',
    name: '연어 샐러디 230g',
    category: '샐러드',
    price_krw: 9900,
    serving_g: 230,
    kcal: 292,
    protein_g: 15.2,
    carb_g: 26.0,
    sugar_g: 6.8,
    fat_g: 14.0,
    sat_fat_g: 3.2,
    sodium_mg: 580,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-salady-beef-warmbowl-300',
    channel: 'fr',
    brand: '샐러디',
    name: '우삼겹 웜볼 300g',
    category: '샐러드',
    price_krw: 8600,
    serving_g: 300,
    kcal: 410,
    protein_g: 18.7,
    carb_g: 52.0,
    sugar_g: 6.0,
    fat_g: 14.2,
    sat_fat_g: 4.8,
    sodium_mg: 690,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-salady-egg-bacon-sand-180',
    channel: 'fr',
    brand: '샐러디',
    name: '에그베이컨 샌드 180g',
    category: '샌드위치/버거',
    price_krw: 6900,
    serving_g: 180,
    kcal: 420,
    protein_g: 18.0,
    carb_g: 44.0,
    sugar_g: 5.5,
    fat_g: 19.0,
    sat_fat_g: 5.2,
    sodium_mg: 740,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-salady-mexican-wrap-220',
    channel: 'fr',
    brand: '샐러디',
    name: '멕시칸 랩 220g',
    category: '샌드위치/버거',
    price_krw: 6900,
    serving_g: 220,
    kcal: 566,
    protein_g: 16.0,
    carb_g: 54.0,
    sugar_g: 7.0,
    fat_g: 31.0,
    sat_fat_g: 8.5,
    sodium_mg: 870,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 3. 맘스터치 (5개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-momstouch-unbelievable-burger-308',
    channel: 'fr',
    brand: '맘스터치',
    name: '언빌리버블 버거 단품 308g',
    category: '샌드위치/버거',
    price_krw: 6200,
    serving_g: 308,
    kcal: 608,
    protein_g: 42.7,
    carb_g: 65.0,
    sugar_g: 14.0,
    fat_g: 20.0,
    sat_fat_g: 5.2,
    sodium_mg: 1280,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '통새우 에그후라이 통가슴살 단백질 42.7g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-momstouch-incredible-burger-305',
    channel: 'fr',
    brand: '맘스터치',
    name: '인크레더블 버거 단품 305g',
    category: '샌드위치/버거',
    price_krw: 5700,
    serving_g: 305,
    kcal: 724,
    protein_g: 32.8,
    carb_g: 68.0,
    sugar_g: 15.0,
    fat_g: 35.0,
    sat_fat_g: 9.8,
    sodium_mg: 1390,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '에그후라이 더블햄 통다리살 단백질 32.8g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-momstouch-golden-mac-cheese-265',
    channel: 'fr',
    brand: '맘스터치',
    name: '골든맥앤치즈 치킨버거 단품 265g',
    category: '샌드위치/버거',
    price_krw: 6200,
    serving_g: 265,
    kcal: 628,
    protein_g: 33.0,
    carb_g: 64.0,
    sugar_g: 11.0,
    fat_g: 27.0,
    sat_fat_g: 7.8,
    sodium_mg: 1210,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-momstouch-cheesestick-2pcs-80',
    channel: 'fr',
    brand: '맘스터치',
    name: '치즈스틱 2조각 80g',
    category: '과자/바',
    price_krw: 2000,
    serving_g: 80,
    kcal: 220,
    protein_g: 12.0,
    carb_g: 18.0,
    sugar_g: 1.5,
    fat_g: 11.0,
    sat_fat_g: 5.5,
    sodium_mg: 380,
    protein_source: 'Q1',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-momstouch-shrimp-burger-175',
    channel: 'fr',
    brand: '맘스터치',
    name: '통새우버거 단품 175g',
    category: '샌드위치/버거',
    price_krw: 3500,
    serving_g: 175,
    kcal: 440,
    protein_g: 14.0,
    carb_g: 52.0,
    sugar_g: 8.0,
    fat_g: 19.0,
    sat_fat_g: 4.5,
    sodium_mg: 820,
    protein_source: 'Q3',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 4. 맥도날드 (7개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-mcdonalds-bacon-tomato-deluxe-240',
    channel: 'fr',
    brand: '맥도날드',
    name: '베이컨 토마토 디럭스 단품 240g',
    category: '샌드위치/버거',
    price_krw: 5800,
    serving_g: 240,
    kcal: 545,
    protein_g: 27.0,
    carb_g: 47.0,
    sugar_g: 11.0,
    fat_g: 28.0,
    sat_fat_g: 10.0,
    sodium_mg: 890,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '순쇠고기 패티 2장과 베이컨 단백질 27g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-1955-burger-255',
    channel: 'fr',
    brand: '맥도날드',
    name: '1955 버거 단품 255g',
    category: '샌드위치/버거',
    price_krw: 6400,
    serving_g: 255,
    kcal: 536,
    protein_g: 28.0,
    carb_g: 46.0,
    sugar_g: 12.0,
    fat_g: 26.5,
    sat_fat_g: 9.5,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '두툼한 113g 순쇠고기 패티 단백질 28g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-cheeseburger-116',
    channel: 'fr',
    brand: '맥도날드',
    name: '치즈버거 단품 116g',
    category: '샌드위치/버거',
    price_krw: 3600,
    serving_g: 116,
    kcal: 317,
    protein_g: 16.0,
    carb_g: 32.0,
    sugar_g: 7.0,
    fat_g: 13.0,
    sat_fat_g: 6.0,
    sodium_mg: 610,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-double-cheeseburger-167',
    channel: 'fr',
    brand: '맥도날드',
    name: '더블 치즈버거 단품 167g',
    category: '샌드위치/버거',
    price_krw: 4800,
    serving_g: 167,
    kcal: 468,
    protein_g: 26.0,
    carb_g: 33.0,
    sugar_g: 7.0,
    fat_g: 25.0,
    sat_fat_g: 12.0,
    sodium_mg: 940,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '패티 2장 치즈 2장 단백질 26g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-chicken-tender-4pcs-120',
    channel: 'fr',
    brand: '맥도날드',
    name: '맥스파이시 치킨 텐더 4조각 120g',
    category: '닭가슴살/육가공',
    price_krw: 5600,
    serving_g: 120,
    kcal: 248,
    protein_g: 23.0,
    carb_g: 14.0,
    sugar_g: 0.5,
    fat_g: 10.8,
    sat_fat_g: 2.1,
    sodium_mg: 690,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '100% 닭안심 순살 단백질 23g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-egg-mcmuffin-139',
    channel: 'fr',
    brand: '맥도날드',
    name: '에그 맥머핀 139g',
    category: '샌드위치/버거',
    price_krw: 3800,
    serving_g: 139,
    kcal: 303,
    protein_g: 19.0,
    carb_g: 29.0,
    sugar_g: 3.0,
    fat_g: 12.0,
    sat_fat_g: 5.0,
    sodium_mg: 640,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-sausage-egg-mcmuffin-166',
    channel: 'fr',
    brand: '맥도날드',
    name: '소시지 에그 맥머핀 166g',
    category: '샌드위치/버거',
    price_krw: 4200,
    serving_g: 166,
    kcal: 450,
    protein_g: 21.0,
    carb_g: 30.0,
    sugar_g: 3.0,
    fat_g: 26.5,
    sat_fat_g: 9.8,
    sodium_mg: 890,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 5. 버거킹 (6개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-burgerking-whole-shrimp-whopper-328',
    channel: 'fr',
    brand: '버거킹',
    name: '통새우와퍼 단품 328g',
    category: '샌드위치/버거',
    price_krw: 7900,
    serving_g: 328,
    kcal: 741,
    protein_g: 33.0,
    carb_g: 68.0,
    sugar_g: 12.0,
    fat_g: 37.0,
    sat_fat_g: 13.0,
    sodium_mg: 1040,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '갈릭페퍼 통새우 직화 패티 단백질 33g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.burgerking.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-burgerking-quattro-cheese-whopper-309',
    channel: 'fr',
    brand: '버거킹',
    name: '콰트로치즈와퍼 단품 309g',
    category: '샌드위치/버거',
    price_krw: 7900,
    serving_g: 309,
    kcal: 769,
    protein_g: 35.0,
    carb_g: 62.0,
    sugar_g: 10.0,
    fat_g: 42.0,
    sat_fat_g: 16.0,
    sodium_mg: 1080,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '4가지 고급 치즈와 순쇠고기 단백질 35g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.burgerking.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-burgerking-cheese-whopper-298',
    channel: 'fr',
    brand: '버거킹',
    name: '치즈와퍼 단품 298g',
    category: '샌드위치/버거',
    price_krw: 7700,
    serving_g: 298,
    kcal: 716,
    protein_g: 33.0,
    carb_g: 58.0,
    sugar_g: 11.0,
    fat_g: 38.0,
    sat_fat_g: 15.0,
    sodium_mg: 1020,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.burgerking.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-burgerking-whopper-junior-158',
    channel: 'fr',
    brand: '버거킹',
    name: '와퍼주니어 단품 158g',
    category: '샌드위치/버거',
    price_krw: 4700,
    serving_g: 158,
    kcal: 399,
    protein_g: 17.0,
    carb_g: 37.0,
    sugar_g: 7.0,
    fat_g: 20.0,
    sat_fat_g: 7.0,
    sodium_mg: 570,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.burgerking.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-burgerking-garlic-bulgogi-whopper-315',
    channel: 'fr',
    brand: '버거킹',
    name: '갈릭불고기와퍼 단품 315g',
    category: '샌드위치/버거',
    price_krw: 7400,
    serving_g: 315,
    kcal: 690,
    protein_g: 31.0,
    carb_g: 64.0,
    sugar_g: 14.0,
    fat_g: 34.0,
    sat_fat_g: 12.0,
    sodium_mg: 950,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.burgerking.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-burgerking-basak-king-4pcs-130',
    channel: 'fr',
    brand: '버거킹',
    name: '바삭킹 4조각 130g',
    category: '닭가슴살/육가공',
    price_krw: 3600,
    serving_g: 130,
    kcal: 340,
    protein_g: 21.0,
    carb_g: 16.0,
    sugar_g: 1.0,
    fat_g: 21.0,
    sat_fat_g: 5.2,
    sodium_mg: 760,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.burgerking.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 6. KFC (5개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-kfc-tower-burger-245',
    channel: 'fr',
    brand: 'KFC',
    name: '타워버거 단품 245g',
    category: '샌드위치/버거',
    price_krw: 6300,
    serving_g: 245,
    kcal: 598,
    protein_g: 32.0,
    carb_g: 54.0,
    sugar_g: 8.0,
    fat_g: 28.0,
    sat_fat_g: 6.8,
    sodium_mg: 1180,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '통가슴살 필렛과 해시브라운 치즈 단백질 32g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kfckorea.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kfc-zinger-blt-burger-238',
    channel: 'fr',
    brand: 'KFC',
    name: '징거BLT 버거 단품 238g',
    category: '샌드위치/버거',
    price_krw: 6700,
    serving_g: 238,
    kcal: 520,
    protein_g: 32.0,
    carb_g: 46.0,
    sugar_g: 7.5,
    fat_g: 22.5,
    sat_fat_g: 5.5,
    sodium_mg: 1040,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '징거 필렛 베이컨 치즈 단백질 32g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kfckorea.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kfc-god-seasoned-chicken-1pc-110',
    channel: 'fr',
    brand: 'KFC',
    name: '갓양념 치킨 1조각 110g',
    category: '닭가슴살/육가공',
    price_krw: 3600,
    serving_g: 110,
    kcal: 325,
    protein_g: 17.0,
    carb_g: 25.0,
    sugar_g: 10.0,
    fat_g: 17.0,
    sat_fat_g: 3.8,
    sodium_mg: 620,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kfckorea.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kfc-hot-cheese-zinger-230',
    channel: 'fr',
    brand: 'KFC',
    name: '핫치즈징거버거 단품 230g',
    category: '샌드위치/버거',
    price_krw: 6600,
    serving_g: 230,
    kcal: 515,
    protein_g: 31.0,
    carb_g: 47.0,
    sugar_g: 7.0,
    fat_g: 22.0,
    sat_fat_g: 5.2,
    sodium_mg: 990,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kfckorea.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kfc-chicken-skin-fry-100',
    channel: 'fr',
    brand: 'KFC',
    name: '닭껍질튀김 100g',
    category: '닭가슴살/육가공',
    price_krw: 3300,
    serving_g: 100,
    kcal: 320,
    protein_g: 12.0,
    carb_g: 20.0,
    sugar_g: 1.0,
    fat_g: 21.0,
    sat_fat_g: 4.8,
    sodium_mg: 580,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kfckorea.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 7. 롯데리아 (5개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-lotteria-bulgogi-burger-188',
    channel: 'fr',
    brand: '롯데리아',
    name: '불고기 버거 단품 188g',
    category: '샌드위치/버거',
    price_krw: 4700,
    serving_g: 188,
    kcal: 476,
    protein_g: 17.0,
    carb_g: 58.0,
    sugar_g: 12.0,
    fat_g: 20.0,
    sat_fat_g: 6.5,
    sodium_mg: 730,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-lotteria-shrimp-burger-179',
    channel: 'fr',
    brand: '롯데리아',
    name: '새우버거 단품 179g',
    category: '샌드위치/버거',
    price_krw: 4700,
    serving_g: 179,
    kcal: 492,
    protein_g: 15.0,
    carb_g: 57.0,
    sugar_g: 9.0,
    fat_g: 22.0,
    sat_fat_g: 5.0,
    sodium_mg: 790,
    protein_source: 'Q3',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-lotteria-double-hanwoo-bulgogi-340',
    channel: 'fr',
    brand: '롯데리아',
    name: '더블 한우불고기 버거 단품 340g',
    category: '샌드위치/버거',
    price_krw: 12400,
    serving_g: 340,
    kcal: 802,
    protein_g: 40.0,
    carb_g: 66.0,
    sugar_g: 15.0,
    fat_g: 42.0,
    sat_fat_g: 16.0,
    sodium_mg: 1240,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '국내산 한우 패티 2장 단백질 40g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-lotteria-ria-miracle-burger-200',
    channel: 'fr',
    brand: '롯데리아',
    name: '리아미라클 버거 단품 200g',
    category: '샌드위치/버거',
    price_krw: 5200,
    serving_g: 200,
    kcal: 474,
    protein_g: 17.0,
    carb_g: 61.0,
    sugar_g: 11.0,
    fat_g: 18.0,
    sat_fat_g: 3.8,
    sodium_mg: 820,
    protein_source: 'Q4',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '대체육 식물성 패티 버거',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-lotteria-fire-wing-4pcs-120',
    channel: 'fr',
    brand: '롯데리아',
    name: '화이어윙 4조각 120g',
    category: '닭가슴살/육가공',
    price_krw: 5300,
    serving_g: 120,
    kcal: 348,
    protein_g: 21.0,
    carb_g: 14.0,
    sugar_g: 1.0,
    fat_g: 23.0,
    sat_fat_g: 5.8,
    sodium_mg: 710,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.lotteria.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 8. 노브랜드버거 (5개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-nbb-meat-mania-burger-285',
    channel: 'fr',
    brand: '노브랜드버거',
    name: '미트 마니아 버거 단품 285g',
    category: '샌드위치/버거',
    price_krw: 6100,
    serving_g: 285,
    kcal: 743,
    protein_g: 36.0,
    carb_g: 51.0,
    sugar_g: 8.0,
    fat_g: 44.0,
    sat_fat_g: 16.0,
    sodium_mg: 1340,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '더블 패티 치즈 계란후라이 단백질 36g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.shinsegaefood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-nbb-double-cheese-bacon-224',
    channel: 'fr',
    brand: '노브랜드버거',
    name: '더블치즈앤베이컨 버거 단품 224g',
    category: '샌드위치/버거',
    price_krw: 5200,
    serving_g: 224,
    kcal: 582,
    protein_g: 25.0,
    carb_g: 48.0,
    sugar_g: 8.0,
    fat_g: 32.0,
    sat_fat_g: 11.0,
    sodium_mg: 1080,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.shinsegaefood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-nbb-sanchez-burger-218',
    channel: 'fr',
    brand: '노브랜드버거',
    name: '산체스 버거 단품 218g',
    category: '샌드위치/버거',
    price_krw: 4700,
    serving_g: 218,
    kcal: 514,
    protein_g: 21.0,
    carb_g: 47.0,
    sugar_g: 7.0,
    fat_g: 27.0,
    sat_fat_g: 8.5,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.shinsegaefood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-nbb-smoky-salsa-burger-200',
    channel: 'fr',
    brand: '노브랜드버거',
    name: '스모키 살사 버거 단품 200g',
    category: '샌드위치/버거',
    price_krw: 4500,
    serving_g: 200,
    kcal: 487,
    protein_g: 20.0,
    carb_g: 46.0,
    sugar_g: 8.0,
    fat_g: 25.0,
    sat_fat_g: 7.5,
    sodium_mg: 890,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.shinsegaefood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-nbb-chicken-caesar-salad-180',
    channel: 'fr',
    brand: '노브랜드버거',
    name: '치킨 시저 샐러드 180g',
    category: '샐러드',
    price_krw: 4300,
    serving_g: 180,
    kcal: 180,
    protein_g: 18.0,
    carb_g: 8.0,
    sugar_g: 2.5,
    fat_g: 8.5,
    sat_fat_g: 2.2,
    sodium_mg: 460,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '담백한 치킨 텐더 시저 샐러드',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.shinsegaefood.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 9. 프랭크버거 (4개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-frankburger-sg-bulgogi-170',
    channel: 'fr',
    brand: '프랭크버거',
    name: 'SG불고기버거 단품 170g',
    category: '샌드위치/버거',
    price_krw: 3800,
    serving_g: 170,
    kcal: 460,
    protein_g: 16.0,
    carb_g: 45.0,
    sugar_g: 9.0,
    fat_g: 24.0,
    sat_fat_g: 7.5,
    sodium_mg: 740,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://frankburger.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-frankburger-bacon-cheese-r-215',
    channel: 'fr',
    brand: '프랭크버거',
    name: '베이컨치즈버거 R 단품 215g',
    category: '샌드위치/버거',
    price_krw: 6900,
    serving_g: 215,
    kcal: 535,
    protein_g: 22.0,
    carb_g: 42.0,
    sugar_g: 8.0,
    fat_g: 31.0,
    sat_fat_g: 11.0,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://frankburger.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-frankburger-shrimp-burger-190',
    channel: 'fr',
    brand: '프랭크버거',
    name: '쉬림프버거 단품 190g',
    category: '샌드위치/버거',
    price_krw: 5000,
    serving_g: 190,
    kcal: 485,
    protein_g: 14.0,
    carb_g: 50.0,
    sugar_g: 7.0,
    fat_g: 25.0,
    sat_fat_g: 4.8,
    sodium_mg: 820,
    protein_source: 'Q3',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://frankburger.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-frankburger-k-bulgogi-180',
    channel: 'fr',
    brand: '프랭크버거',
    name: 'K불고기버거 단품 180g',
    category: '샌드위치/버거',
    price_krw: 4300,
    serving_g: 180,
    kcal: 470,
    protein_g: 17.0,
    carb_g: 46.0,
    sugar_g: 10.0,
    fat_g: 24.0,
    sat_fat_g: 7.8,
    sodium_mg: 790,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://frankburger.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 10. 한솥도시락 (7개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-hansot-jindallae-dosirak-510',
    channel: 'fr',
    brand: '한솥도시락',
    name: '진달래 도시락 510g',
    category: '도시락',
    price_krw: 7800,
    serving_g: 510,
    kcal: 812,
    protein_g: 34.0,
    carb_g: 104.0,
    sugar_g: 10.0,
    fat_g: 29.0,
    sat_fat_g: 7.8,
    sodium_mg: 1350,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '떡갈비 돈까스 새우튀김 치킨 단백질 34g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-gaenari-dosirak-430',
    channel: 'fr',
    brand: '한솥도시락',
    name: '개나리 도시락 430g',
    category: '도시락',
    price_krw: 8500,
    serving_g: 430,
    kcal: 680,
    protein_g: 30.0,
    carb_g: 88.0,
    sugar_g: 9.0,
    fat_g: 23.0,
    sat_fat_g: 5.8,
    sodium_mg: 1120,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '고등어데리야끼 소불고기 치킨 단백질 30g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-beef-bulgogi-dosirak-400',
    channel: 'fr',
    brand: '한솥도시락',
    name: '소불고기 도시락 400g',
    category: '도시락',
    price_krw: 5500,
    serving_g: 400,
    kcal: 630,
    protein_g: 28.0,
    carb_g: 82.0,
    sugar_g: 9.0,
    fat_g: 21.0,
    sat_fat_g: 6.2,
    sodium_mg: 1080,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-spam-kimchi-friedrice-350',
    channel: 'fr',
    brand: '한솥도시락',
    name: '스팸김치볶음밥 350g',
    category: '도시락',
    price_krw: 4700,
    serving_g: 350,
    kcal: 610,
    protein_g: 18.0,
    carb_g: 85.0,
    sugar_g: 6.0,
    fat_g: 22.0,
    sat_fat_g: 6.5,
    sodium_mg: 1220,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-beef-bibimbap-410',
    channel: 'fr',
    brand: '한솥도시락',
    name: '소불고기 감초고추장 비빔밥 410g',
    category: '도시락',
    price_krw: 5400,
    serving_g: 410,
    kcal: 580,
    protein_g: 21.0,
    carb_g: 92.0,
    sugar_g: 11.0,
    fat_g: 14.0,
    sat_fat_g: 3.8,
    sodium_mg: 940,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-tuna-veggie-bibimbap-390',
    channel: 'fr',
    brand: '한솥도시락',
    name: '참치야채 감초고추장 비빔밥 390g',
    category: '도시락',
    price_krw: 3900,
    serving_g: 390,
    kcal: 490,
    protein_g: 19.0,
    carb_g: 84.0,
    sugar_g: 8.0,
    fat_g: 8.5,
    sat_fat_g: 1.8,
    sodium_mg: 820,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-hansot-kimchi-pork-bowl-370',
    channel: 'fr',
    brand: '한솥도시락',
    name: '김치제육덮밥 370g',
    category: '도시락',
    price_krw: 4900,
    serving_g: 370,
    kcal: 590,
    protein_g: 23.0,
    carb_g: 78.0,
    sugar_g: 9.0,
    fat_g: 20.5,
    sat_fat_g: 5.5,
    sodium_mg: 1150,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.hsd.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 11. 치킨 프랜차이즈 (굽네/교촌/BBQ/BHC/푸라닭/처갓집) (13개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-goobne-galbi-boneless-200',
    channel: 'fr',
    brand: '굽네치킨',
    name: '굽네 갈비천왕 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 10500,
    serving_g: 200,
    kcal: 440,
    protein_g: 45.0,
    carb_g: 16.0,
    sugar_g: 8.0,
    fat_g: 22.0,
    sat_fat_g: 5.5,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '정통 갈비양념 오븐구이 단백질 45g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.goobne.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-goobne-oven-crispy-boneless-200',
    channel: 'fr',
    brand: '굽네치킨',
    name: '굽네 오븐바사삭 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 9500,
    serving_g: 200,
    kcal: 435,
    protein_g: 44.0,
    carb_g: 12.0,
    sugar_g: 1.0,
    fat_g: 23.0,
    sat_fat_g: 5.2,
    sodium_mg: 790,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '현미가루 입힌 바삭 오븐구이 단백질 44g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.goobne.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kyochon-half-boneless-200',
    channel: 'fr',
    brand: '교촌치킨',
    name: '교촌 반반 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11000,
    serving_g: 200,
    kcal: 525,
    protein_g: 45.5,
    carb_g: 19.0,
    sugar_g: 5.0,
    fat_g: 29.5,
    sat_fat_g: 6.4,
    sodium_mg: 950,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kyochon.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kyochon-salsal-fried-200',
    channel: 'fr',
    brand: '교촌치킨',
    name: '교촌 살살후라이드 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 10000,
    serving_g: 200,
    kcal: 510,
    protein_g: 44.0,
    carb_g: 22.0,
    sugar_g: 1.0,
    fat_g: 27.0,
    sat_fat_g: 5.8,
    sodium_mg: 820,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '쌀가루 가슴살과 안심 단백질 44g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kyochon.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-bbq-inner-tender-10pcs-200',
    channel: 'fr',
    brand: 'BBQ',
    name: '황금올리브치킨 속안심 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 10000,
    serving_g: 200,
    kcal: 460,
    protein_g: 44.0,
    carb_g: 18.0,
    sugar_g: 1.0,
    fat_g: 23.5,
    sat_fat_g: 4.8,
    sodium_mg: 790,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '100% 닭안심 순살 단백질 44g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.bbq.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-bbq-king-galbi-boneless-200',
    channel: 'fr',
    brand: 'BBQ',
    name: '극한왕갈비치킨 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11500,
    serving_g: 200,
    kcal: 520,
    protein_g: 39.0,
    carb_g: 26.0,
    sugar_g: 9.0,
    fat_g: 28.5,
    sat_fat_g: 6.2,
    sodium_mg: 960,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.bbq.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-bhc-bburingkle-boneless-200',
    channel: 'fr',
    brand: 'BHC',
    name: '뿌링클 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11000,
    serving_g: 200,
    kcal: 560,
    protein_g: 42.0,
    carb_g: 30.0,
    sugar_g: 8.0,
    fat_g: 30.0,
    sat_fat_g: 7.2,
    sodium_mg: 980,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: 'BHC 시그니처 닭가슴살 순살 뿌링클',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.bhc.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-bhc-goldking-boneless-200',
    channel: 'fr',
    brand: 'BHC',
    name: '골드킹 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11000,
    serving_g: 200,
    kcal: 530,
    protein_g: 41.0,
    carb_g: 27.0,
    sugar_g: 9.0,
    fat_g: 28.5,
    sat_fat_g: 6.5,
    sodium_mg: 940,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.bhc.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-puradak-black-aglio-boneless-200',
    channel: 'fr',
    brand: '푸라닭',
    name: '블랙알리오 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11000,
    serving_g: 200,
    kcal: 490,
    protein_g: 43.0,
    carb_g: 18.0,
    sugar_g: 6.0,
    fat_g: 27.0,
    sat_fat_g: 5.8,
    sodium_mg: 880,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '오븐 후라이드 통다리살 갈릭 간장',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://puradakchicken.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-puradak-chili-mayo-boneless-200',
    channel: 'fr',
    brand: '푸라닭',
    name: '고추마요 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11000,
    serving_g: 200,
    kcal: 520,
    protein_g: 41.0,
    carb_g: 20.0,
    sugar_g: 7.0,
    fat_g: 30.5,
    sat_fat_g: 6.8,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://puradakchicken.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-puradak-original-boneless-200',
    channel: 'fr',
    brand: '푸라닭',
    name: '푸라닭 오리지널 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 10000,
    serving_g: 200,
    kcal: 460,
    protein_g: 45.0,
    carb_g: 8.0,
    sugar_g: 0.5,
    fat_g: 27.5,
    sat_fat_g: 5.5,
    sodium_mg: 740,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '오븐 후라이드 공법 담백한 순살 단백질 45g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://puradakchicken.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-cheogajip-supreme-boneless-200',
    channel: 'fr',
    brand: '처갓집양념치킨',
    name: '슈프림양념치킨 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11500,
    serving_g: 200,
    kcal: 580,
    protein_g: 36.0,
    carb_g: 34.0,
    sugar_g: 12.0,
    fat_g: 33.0,
    sat_fat_g: 7.5,
    sodium_mg: 990,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.cheogajip.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-cheogajip-seasoned-boneless-200',
    channel: 'fr',
    brand: '처갓집양념치킨',
    name: '처갓집 양념치킨 순살 (200g 1회 기준)',
    category: '닭가슴살/육가공',
    price_krw: 11000,
    serving_g: 200,
    kcal: 540,
    protein_g: 38.0,
    carb_g: 30.0,
    sugar_g: 11.0,
    fat_g: 29.5,
    sat_fat_g: 6.8,
    sodium_mg: 940,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.cheogajip.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 12. 포케 전문점 (슬로우캘리 & 포케올데이) (7개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-slowcali-spicy-tuna-poke-380',
    channel: 'fr',
    brand: '슬로우캘리',
    name: '스파이시 참치 포케 380g',
    category: '샐러드',
    price_krw: 11500,
    serving_g: 380,
    kcal: 550,
    protein_g: 28.0,
    carb_g: 67.0,
    sugar_g: 7.2,
    fat_g: 17.5,
    sat_fat_g: 3.0,
    sodium_mg: 820,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '매콤 스리라차 참치 단백질 28g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://slowcali.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-slowcali-spicy-salmon-poke-380',
    channel: 'fr',
    brand: '슬로우캘리',
    name: '스파이시 연어 포케 380g',
    category: '샐러드',
    price_krw: 12500,
    serving_g: 380,
    kcal: 580,
    protein_g: 26.0,
    carb_g: 65.0,
    sugar_g: 7.5,
    fat_g: 22.0,
    sat_fat_g: 3.8,
    sodium_mg: 790,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '스파이시 마요 연어 단백질 26g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://slowcali.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-slowcali-wasabi-salmon-poke-380',
    channel: 'fr',
    brand: '슬로우캘리',
    name: '와사비 렌치 연어 포케 380g',
    category: '샐러드',
    price_krw: 12500,
    serving_g: 380,
    kcal: 590,
    protein_g: 26.0,
    carb_g: 64.0,
    sugar_g: 7.0,
    fat_g: 23.5,
    sat_fat_g: 4.2,
    sodium_mg: 760,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://slowcali.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-slowcali-garlic-shrimp-bowl-350',
    channel: 'fr',
    brand: '슬로우캘리',
    name: '하와이안 갈릭 쉬림프 350g',
    category: '샐러드',
    price_krw: 12500,
    serving_g: 350,
    kcal: 480,
    protein_g: 22.0,
    carb_g: 62.0,
    sugar_g: 5.5,
    fat_g: 14.5,
    sat_fat_g: 3.2,
    sodium_mg: 710,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '통새우 갈릭 버터 현미밥 보울',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://slowcali.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-pokeallday-salmon-brownrice-360',
    channel: 'fr',
    brand: '포케올데이',
    name: '현미밥 연어 포케 360g',
    category: '샐러드',
    price_krw: 12900,
    serving_g: 360,
    kcal: 490,
    protein_g: 25.0,
    carb_g: 61.0,
    sugar_g: 6.2,
    fat_g: 15.0,
    sat_fat_g: 3.0,
    sodium_mg: 620,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '신선한 생연어 슈퍼푸드 현미밥 포케',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://pokeallday.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-pokeallday-beef-brownrice-360',
    channel: 'fr',
    brand: '포케올데이',
    name: '현미밥 우삼겹 포케 360g',
    category: '샐러드',
    price_krw: 11900,
    serving_g: 360,
    kcal: 560,
    protein_g: 22.0,
    carb_g: 60.0,
    sugar_g: 6.0,
    fat_g: 24.5,
    sat_fat_g: 7.2,
    sodium_mg: 740,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://pokeallday.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-pokeallday-rawbeef-buckwheat-350',
    channel: 'fr',
    brand: '포케올데이',
    name: '메밀면 육회 포케 350g',
    category: '샐러드',
    price_krw: 12900,
    serving_g: 350,
    kcal: 475,
    protein_g: 26.0,
    carb_g: 56.0,
    sugar_g: 7.5,
    fat_g: 14.5,
    sat_fat_g: 3.8,
    sodium_mg: 710,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '신선한 소고기 육회와 메밀면 단백질 26g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://pokeallday.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 13. 카페 식사 대용 (스타벅스 & 투썸플레이스) (7개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-starbucks-bacon-cheese-toast-130',
    channel: 'fr',
    brand: '스타벅스',
    name: '베이컨 치즈 토스트 130g',
    category: '샌드위치/버거',
    price_krw: 4900,
    serving_g: 130,
    kcal: 355,
    protein_g: 14.0,
    carb_g: 32.0,
    sugar_g: 4.5,
    fat_g: 19.0,
    sat_fat_g: 7.0,
    sodium_mg: 690,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.starbucks.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-starbucks-sweetpumpkin-egg-190',
    channel: 'fr',
    brand: '스타벅스',
    name: '단호박 에그 샐러드 샌드위치 190g',
    category: '샌드위치/버거',
    price_krw: 5500,
    serving_g: 190,
    kcal: 337,
    protein_g: 13.0,
    carb_g: 45.0,
    sugar_g: 8.0,
    fat_g: 11.5,
    sat_fat_g: 3.2,
    sodium_mg: 620,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.starbucks.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-starbucks-chicken-tomato-cheese-205',
    channel: 'fr',
    brand: '스타벅스',
    name: '치킨 토마토 치즈 샌드위치 205g',
    category: '샌드위치/버거',
    price_krw: 6300,
    serving_g: 205,
    kcal: 420,
    protein_g: 20.0,
    carb_g: 46.0,
    sugar_g: 6.0,
    fat_g: 16.5,
    sat_fat_g: 5.5,
    sodium_mg: 820,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '담백한 닭가슴살 토마토 모짜렐라 단백질 20g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.starbucks.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-starbucks-cobb-salad-mealbox-195',
    channel: 'fr',
    brand: '스타벅스',
    name: '콥 & 화이트 샐러드 밀 박스 195g',
    category: '샐러드',
    price_krw: 6500,
    serving_g: 195,
    kcal: 198,
    protein_g: 17.0,
    carb_g: 13.0,
    sugar_g: 3.8,
    fat_g: 8.4,
    sat_fat_g: 2.2,
    sodium_mg: 520,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '닭가슴살과 새우 달걀 콥 샐러드 밀박스',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.starbucks.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-twosome-all-day-beef-panini-195',
    channel: 'fr',
    brand: '투썸플레이스',
    name: '올데이 비프 파니니 195g',
    category: '샌드위치/버거',
    price_krw: 6900,
    serving_g: 195,
    kcal: 450,
    protein_g: 22.0,
    carb_g: 45.0,
    sugar_g: 6.0,
    fat_g: 19.0,
    sat_fat_g: 6.5,
    sodium_mg: 920,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '소불고기와 프로볼로네 치즈 단백질 22g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.twosome.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-twosome-bbq-chicken-panini-200',
    channel: 'fr',
    brand: '투썸플레이스',
    name: '바베큐 치킨 파니니 200g',
    category: '샌드위치/버거',
    price_krw: 6900,
    serving_g: 200,
    kcal: 440,
    protein_g: 21.0,
    carb_g: 47.0,
    sugar_g: 7.0,
    fat_g: 17.5,
    sat_fat_g: 5.5,
    sodium_mg: 880,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.twosome.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-twosome-shrimp-egg-salad-210',
    channel: 'fr',
    brand: '투썸플레이스',
    name: '쉬림프 에그 샐러드 210g',
    category: '샐러드',
    price_krw: 7800,
    serving_g: 210,
    kcal: 210,
    protein_g: 16.0,
    carb_g: 14.0,
    sugar_g: 5.0,
    fat_g: 9.5,
    sat_fat_g: 2.2,
    sodium_mg: 490,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.twosome.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // 14. 피자 프랜차이즈 (도미노피자 / 피자헛 - 2조각 1회 섭취 기준) (4개)
  // ─────────────────────────────────────────────────────────────
  {
    menu_id: 'fr-domino-black-tiger-shrimp-thin-170',
    channel: 'fr',
    brand: '도미노피자',
    name: '블랙타이거 슈림프 씬 (2조각 기준)',
    category: '기타',
    price_krw: 8000,
    serving_g: 170,
    kcal: 360,
    protein_g: 18.0,
    carb_g: 42.0,
    sugar_g: 5.0,
    fat_g: 13.0,
    sat_fat_g: 4.8,
    sodium_mg: 720,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '대왕새우 와규 크럼블 씬도우 2조각 단백질 18g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://web.dominos.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-domino-potato-thin-180',
    channel: 'fr',
    brand: '도미노피자',
    name: '포테이토 씬 피자 (2조각 기준)',
    category: '기타',
    price_krw: 7000,
    serving_g: 180,
    kcal: 370,
    protein_g: 16.0,
    carb_g: 46.0,
    sugar_g: 4.0,
    fat_g: 14.0,
    sat_fat_g: 5.2,
    sodium_mg: 690,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://web.dominos.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-domino-real-bulgogi-thin-175',
    channel: 'fr',
    brand: '도미노피자',
    name: '리얼불고기 씬 피자 (2조각 기준)',
    category: '기타',
    price_krw: 7500,
    serving_g: 175,
    kcal: 375,
    protein_g: 18.0,
    carb_g: 44.0,
    sugar_g: 6.0,
    fat_g: 14.0,
    sat_fat_g: 5.5,
    sodium_mg: 740,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://web.dominos.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-pizzahut-rib-steak-bite-190',
    channel: 'fr',
    brand: '피자헛',
    name: '립스테이크 바이트 피자 (2조각 기준)',
    category: '기타',
    price_krw: 8500,
    serving_g: 190,
    kcal: 420,
    protein_g: 20.0,
    carb_g: 48.0,
    sugar_g: 6.5,
    fat_g: 16.0,
    sat_fat_g: 6.8,
    sodium_mg: 780,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '갈비 스테이크와 치즈 바이트 2조각 단백질 20g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.pizzahut.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  }
];

function main() {
  const seedPath = path.join(rootDir, 'data', 'seed.json');
  const existingSeed = JSON.parse(fs.readFileSync(seedPath, 'utf-8'));
  const existingIdSet = new Set(existingSeed.map(x => x.menu_id));

  console.log(`기존 DB 품목 수: ${existingSeed.length}개`);
  console.log(`신규 프랜차이즈 3차 추가 대상: ${batch3Items.length}개`);

  // QA 검증
  let failCount = 0;
  let warnCount = 0;
  for (const item of batch3Items) {
    const qa = validateMenuQA(item, existingIdSet);
    if (!qa.valid) {
      console.error(`❌ [QA 에러] ${item.name}:`, qa.errors);
      failCount++;
    }
    if (qa.warnings.length > 0) {
      console.warn(`⚠️ [QA 경고] ${item.name}:`, qa.warnings);
      warnCount++;
    }
    existingIdSet.add(item.menu_id);
  }

  if (failCount > 0) {
    console.error(`💥 QA 에러 ${failCount}건 발생으로 중단합니다.`);
    process.exit(1);
  }

  console.log(`✅ 신규 ${batch3Items.length}개 품목 R1~R5 QA 통과 완료 (경고: ${warnCount}건)`);

  // 병합
  const merged = [...existingSeed, ...batch3Items];
  fs.writeFileSync(seedPath, JSON.stringify(merged, null, 2), 'utf-8');
  console.log(`💾 data/seed.json 업데이트 완료! (총 ${merged.length}개)`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
