// scripts/expand_full_stages.js
// 1단계(외식 fr), 2단계(편의점 cvs 삼각김밥/김밥/샌드위치), 3단계(대형마트/코스트코/수산물 mart), 4단계(식단 플랫폼 HMR online) 90개 품목 확장
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { validateMenuQA } from '../js/qa.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

export const newProducts = [
  // ─────────────────────────────────────────────────────────────
  // [1단계: 외식 프랜차이즈 (channel: 'fr')] 40개
  // ─────────────────────────────────────────────────────────────
  // 1. 맘스터치 (7개)
  {
    menu_id: 'fr-momstouch-fillet-burger-212',
    channel: 'fr',
    brand: '맘스터치',
    name: '휠렛버거 단품 212g',
    category: '샌드위치/버거',
    price_krw: 4700,
    serving_g: 212,
    kcal: 586,
    protein_g: 38.9,
    carb_g: 61.0,
    sugar_g: 9.0,
    fat_g: 21.0,
    sat_fat_g: 4.8,
    sodium_mg: 996,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '통닭가슴살 패티 단백질 38.9g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-momstouch-deep-cheese-burger-226',
    channel: 'fr',
    brand: '맘스터치',
    name: '딥치즈버거 단품 226g',
    category: '샌드위치/버거',
    price_krw: 5100,
    serving_g: 226,
    kcal: 607,
    protein_g: 30.5,
    carb_g: 58.0,
    sugar_g: 9.0,
    fat_g: 28.0,
    sat_fat_g: 8.5,
    sodium_mg: 1083,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-momstouch-thigh-burger-230',
    channel: 'fr',
    brand: '맘스터치',
    name: '싸이버거 단품 230g',
    category: '샌드위치/버거',
    price_krw: 4600,
    serving_g: 230,
    kcal: 594,
    protein_g: 28.0,
    carb_g: 61.0,
    sugar_g: 12.0,
    fat_g: 27.0,
    sat_fat_g: 6.8,
    sodium_mg: 1009,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-momstouch-white-garlic-burger-248',
    channel: 'fr',
    brand: '맘스터치',
    name: '화이트갈릭버거 단품 248g',
    category: '샌드위치/버거',
    price_krw: 5200,
    serving_g: 248,
    kcal: 699,
    protein_g: 38.2,
    carb_g: 65.0,
    sugar_g: 12.0,
    fat_g: 32.0,
    sat_fat_g: 8.1,
    sodium_mg: 1238,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '더블 햄 통가슴살 패티 단백질 38g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-momstouch-spicy-thigh-burger-225',
    channel: 'fr',
    brand: '맘스터치',
    name: '불싸이버거 단품 225g',
    category: '샌드위치/버거',
    price_krw: 4800,
    serving_g: 225,
    kcal: 543,
    protein_g: 27.0,
    carb_g: 57.0,
    sugar_g: 11.0,
    fat_g: 23.0,
    sat_fat_g: 5.5,
    sodium_mg: 1134,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-momstouch-fried-thigh-boneless-300',
    channel: 'fr',
    brand: '맘스터치',
    name: '후라이드 싸이순살 치킨 300g',
    category: '닭가슴살/육가공',
    price_krw: 11900,
    serving_g: 300,
    kcal: 876,
    protein_g: 49.0,
    carb_g: 48.0,
    sugar_g: 4.0,
    fat_g: 54.0,
    sat_fat_g: 11.0,
    sodium_mg: 1420,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-momstouch-cajun-tteokgangjeong-r-250',
    channel: 'fr',
    brand: '맘스터치',
    name: '케이준 떡강정 R 250g',
    category: '닭가슴살/육가공',
    price_krw: 4400,
    serving_g: 250,
    kcal: 652,
    protein_g: 29.0,
    carb_g: 82.0,
    sugar_g: 28.0,
    fat_g: 24.0,
    sat_fat_g: 5.2,
    sodium_mg: 1120,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://momstouch.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 2. 써브웨이 (8개)
  {
    menu_id: 'fr-subway-rotisserie-chicken-15cm-247',
    channel: 'fr',
    brand: '써브웨이',
    name: '로티세리 바비큐 치킨 15cm',
    category: '샌드위치/버거',
    price_krw: 7300,
    serving_g: 247,
    kcal: 327,
    protein_g: 29.3,
    carb_g: 40.2,
    sugar_g: 7.8,
    fat_g: 6.1,
    sat_fat_g: 1.5,
    sodium_mg: 536,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '손으로 찢은 바비큐 치킨 단백질 29g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-roast-chicken-15cm-247',
    channel: 'fr',
    brand: '써브웨이',
    name: '로스트 치킨 15cm',
    category: '샌드위치/버거',
    price_krw: 7300,
    serving_g: 247,
    kcal: 300,
    protein_g: 26.0,
    carb_g: 40.0,
    sugar_g: 7.9,
    fat_g: 4.1,
    sat_fat_g: 1.1,
    sodium_mg: 552,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '오븐에 구운 닭가슴살 패티 단백질 26g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-chicken-slice-15cm-221',
    channel: 'fr',
    brand: '써브웨이',
    name: '치킨 슬라이스 15cm',
    category: '샌드위치/버거',
    price_krw: 6500,
    serving_g: 221,
    kcal: 265,
    protein_g: 18.6,
    carb_g: 39.5,
    sugar_g: 7.5,
    fat_g: 3.7,
    sat_fat_g: 0.9,
    sodium_mg: 692,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '담백한 닭가슴살 햄 샌드위치',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-k-bbq-15cm-245',
    channel: 'fr',
    brand: '써브웨이',
    name: 'K-바비큐 15cm',
    category: '샌드위치/버거',
    price_krw: 7700,
    serving_g: 245,
    kcal: 372,
    protein_g: 25.4,
    carb_g: 47.6,
    sugar_g: 12.8,
    fat_g: 8.9,
    sat_fat_g: 2.7,
    sodium_mg: 830,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-steak-and-cheese-15cm-245',
    channel: 'fr',
    brand: '써브웨이',
    name: '스테이크 & 치즈 15cm',
    category: '샌드위치/버거',
    price_krw: 7900,
    serving_g: 245,
    kcal: 355,
    protein_g: 28.1,
    carb_g: 39.3,
    sugar_g: 8.6,
    fat_g: 9.2,
    sat_fat_g: 4.1,
    sodium_mg: 773,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '직화 비프 스테이크 단백질 28g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-pulled-pork-bbq-15cm-248',
    channel: 'fr',
    brand: '써브웨이',
    name: '풀드포크 바비큐 15cm',
    category: '샌드위치/버거',
    price_krw: 7200,
    serving_g: 248,
    kcal: 327,
    protein_g: 24.8,
    carb_g: 43.1,
    sugar_g: 8.9,
    fat_g: 6.0,
    sat_fat_g: 1.8,
    sodium_mg: 686,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-egg-mayo-15cm-238',
    channel: 'fr',
    brand: '써브웨이',
    name: '에그마요 15cm',
    category: '샌드위치/버거',
    price_krw: 5500,
    serving_g: 238,
    kcal: 416,
    protein_g: 15.0,
    carb_g: 39.7,
    sugar_g: 7.6,
    fat_g: 21.7,
    sat_fat_g: 5.1,
    sodium_mg: 554,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-subway-shrimp-15cm-198',
    channel: 'fr',
    brand: '써브웨이',
    name: '쉬림프 15cm',
    category: '샌드위치/버거',
    price_krw: 7600,
    serving_g: 198,
    kcal: 241,
    protein_g: 14.6,
    carb_g: 39.0,
    sugar_g: 7.6,
    fat_g: 2.8,
    sat_fat_g: 0.6,
    sodium_mg: 434,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.subway.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 3. 샐러디 (6개)
  {
    menu_id: 'fr-salady-tandanji-salad-240',
    channel: 'fr',
    brand: '샐러디',
    name: '탄단지 샐러디 240g',
    category: '샐러드',
    price_krw: 8300,
    serving_g: 240,
    kcal: 371,
    protein_g: 16.7,
    carb_g: 36.4,
    sugar_g: 9.8,
    fat_g: 18.0,
    sat_fat_g: 3.5,
    sodium_mg: 590,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '치킨 스윗포테이토 견과류 균형식',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-salady-chili-bacon-warmbowl-300',
    channel: 'fr',
    brand: '샐러디',
    name: '칠리베이컨 웜볼 300g',
    category: '샐러드',
    price_krw: 7900,
    serving_g: 300,
    kcal: 485,
    protein_g: 20.8,
    carb_g: 64.0,
    sugar_g: 8.2,
    fat_g: 16.2,
    sat_fat_g: 4.2,
    sodium_mg: 780,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-salady-roast-chicken-leg-salad-260',
    channel: 'fr',
    brand: '샐러디',
    name: '로스트닭다리살 샐러디 260g',
    category: '샐러드',
    price_krw: 9500,
    serving_g: 260,
    kcal: 337,
    protein_g: 18.9,
    carb_g: 18.2,
    sugar_g: 6.4,
    fat_g: 21.0,
    sat_fat_g: 4.8,
    sodium_mg: 620,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-salady-beef-buckwheat-salad-290',
    channel: 'fr',
    brand: '샐러디',
    name: '우삼겹 메밀면 샐러디 290g',
    category: '샐러드',
    price_krw: 8900,
    serving_g: 290,
    kcal: 302,
    protein_g: 19.3,
    carb_g: 32.5,
    sugar_g: 5.1,
    fat_g: 10.8,
    sat_fat_g: 3.9,
    sodium_mg: 710,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-salady-chicken-sausage-warmwrap-245',
    channel: 'fr',
    brand: '샐러디',
    name: '치킨소시지 웜랩 245g',
    category: '샌드위치/버거',
    price_krw: 7700,
    serving_g: 245,
    kcal: 475,
    protein_g: 19.8,
    carb_g: 58.2,
    sugar_g: 7.1,
    fat_g: 18.5,
    sat_fat_g: 5.2,
    sodium_mg: 860,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-salady-bbq-chicken-warmbowl-310',
    channel: 'fr',
    brand: '샐러디',
    name: '바비큐치킨 웜볼 310g',
    category: '샐러드',
    price_krw: 8900,
    serving_g: 310,
    kcal: 452,
    protein_g: 22.4,
    carb_g: 62.0,
    sugar_g: 9.1,
    fat_g: 12.8,
    sat_fat_g: 2.9,
    sodium_mg: 740,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://salady.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 4. 맥도날드 (6개)
  {
    menu_id: 'fr-mcdonalds-double-quarter-pounder-275',
    channel: 'fr',
    brand: '맥도날드',
    name: '더블 쿼터파운더 치즈 단품 275g',
    category: '샌드위치/버거',
    price_krw: 7700,
    serving_g: 275,
    kcal: 770,
    protein_g: 50.0,
    carb_g: 42.0,
    sugar_g: 10.0,
    fat_g: 44.0,
    sat_fat_g: 20.0,
    sodium_mg: 1290,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '순쇠고기 패티 2장 단백질 50g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-quarter-pounder-cheese-198',
    channel: 'fr',
    brand: '맥도날드',
    name: '쿼터파운더 치즈 단품 198g',
    category: '샌드위치/버거',
    price_krw: 5700,
    serving_g: 198,
    kcal: 536,
    protein_g: 31.0,
    carb_g: 38.0,
    sugar_g: 10.0,
    fat_g: 28.0,
    sat_fat_g: 13.0,
    sodium_mg: 954,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-shanghai-burger-235',
    channel: 'fr',
    brand: '맥도날드',
    name: '맥스파이시 상하이 버거 단품 235g',
    category: '샌드위치/버거',
    price_krw: 5500,
    serving_g: 235,
    kcal: 501,
    protein_g: 24.0,
    carb_g: 60.0,
    sugar_g: 10.0,
    fat_g: 19.0,
    sat_fat_g: 3.2,
    sodium_mg: 1032,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-mcnuggets-6pcs-108',
    channel: 'fr',
    brand: '맥도날드',
    name: '맥너겟 6조각 108g',
    category: '닭가슴살/육가공',
    price_krw: 3800,
    serving_g: 108,
    kcal: 263,
    protein_g: 16.0,
    carb_g: 17.0,
    sugar_g: 0.5,
    fat_g: 15.0,
    sat_fat_g: 2.8,
    sodium_mg: 556,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-egg-bulgogi-burger-171',
    channel: 'fr',
    brand: '맥도날드',
    name: '에그 불고기 버거 단품 171g',
    category: '샌드위치/버거',
    price_krw: 3900,
    serving_g: 171,
    kcal: 492,
    protein_g: 19.0,
    carb_g: 48.0,
    sugar_g: 14.0,
    fat_g: 25.0,
    sat_fat_g: 6.8,
    sodium_mg: 830,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-mcdonalds-big-mac-213',
    channel: 'fr',
    brand: '맥도날드',
    name: '빅맥 단품 213g',
    category: '샌드위치/버거',
    price_krw: 5500,
    serving_g: 213,
    kcal: 582,
    protein_g: 27.0,
    carb_g: 46.0,
    sugar_g: 8.0,
    fat_g: 31.0,
    sat_fat_g: 11.0,
    sodium_mg: 902,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.mcdonalds.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 5. KFC (5개)
  {
    menu_id: 'fr-kfc-zinger-burger-220',
    channel: 'fr',
    brand: 'KFC',
    name: '징거버거 단품 220g',
    category: '샌드위치/버거',
    price_krw: 5800,
    serving_g: 220,
    kcal: 472,
    protein_g: 30.0,
    carb_g: 45.0,
    sugar_g: 7.0,
    fat_g: 19.0,
    sat_fat_g: 3.5,
    sodium_mg: 910,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '통가슴살 필렛 단백질 30g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kfckorea.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kfc-tender-4pcs-120',
    channel: 'fr',
    brand: 'KFC',
    name: '텐더 4조각 120g',
    category: '닭가슴살/육가공',
    price_krw: 5200,
    serving_g: 120,
    kcal: 260,
    protein_g: 24.0,
    carb_g: 15.0,
    sugar_g: 0.5,
    fat_g: 11.0,
    sat_fat_g: 2.2,
    sodium_mg: 740,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 1,
    claim_text: '순수 닭안심살 단백질 24g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kfckorea.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kfc-black-label-chicken-1pc-85',
    channel: 'fr',
    brand: 'KFC',
    name: '블랙라벨 치킨 1조각 85g',
    category: '닭가슴살/육가공',
    price_krw: 3400,
    serving_g: 85,
    kcal: 238,
    protein_g: 17.0,
    carb_g: 11.0,
    sugar_g: 1.0,
    fat_g: 14.0,
    sat_fat_g: 3.8,
    sodium_mg: 520,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kfckorea.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kfc-hot-crispy-chicken-1pc-100',
    channel: 'fr',
    brand: 'KFC',
    name: '핫크리스피 치킨 1조각 100g',
    category: '닭가슴살/육가공',
    price_krw: 3300,
    serving_g: 100,
    kcal: 271,
    protein_g: 18.0,
    carb_g: 13.0,
    sugar_g: 0.5,
    fat_g: 16.0,
    sat_fat_g: 3.6,
    sodium_mg: 590,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kfckorea.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-kfc-original-chicken-1pc-100',
    channel: 'fr',
    brand: 'KFC',
    name: '오리지널 치킨 1조각 100g',
    category: '닭가슴살/육가공',
    price_krw: 3300,
    serving_g: 100,
    kcal: 258,
    protein_g: 19.0,
    carb_g: 9.0,
    sugar_g: 0.2,
    fat_g: 16.0,
    sat_fat_g: 4.1,
    sodium_mg: 640,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.kfckorea.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 6. 버거킹 (3개)
  {
    menu_id: 'fr-burgerking-whopper-278',
    channel: 'fr',
    brand: '버거킹',
    name: '와퍼 단품 278g',
    category: '샌드위치/버거',
    price_krw: 7100,
    serving_g: 278,
    kcal: 619,
    protein_g: 29.0,
    carb_g: 57.0,
    sugar_g: 11.0,
    fat_g: 31.0,
    sat_fat_g: 12.0,
    sodium_mg: 809,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.burgerking.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-burgerking-long-chicken-burger-210',
    channel: 'fr',
    brand: '버거킹',
    name: '롱치킨버거 단품 210g',
    category: '샌드위치/버거',
    price_krw: 4700,
    serving_g: 210,
    kcal: 571,
    protein_g: 24.0,
    carb_g: 54.0,
    sugar_g: 7.0,
    fat_g: 29.0,
    sat_fat_g: 6.0,
    sodium_mg: 1050,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.burgerking.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-burgerking-nugget-king-8pcs-152',
    channel: 'fr',
    brand: '버거킹',
    name: '너겟킹 8조각 152g',
    category: '닭가슴살/육가공',
    price_krw: 3000,
    serving_g: 152,
    kcal: 372,
    protein_g: 18.0,
    carb_g: 27.0,
    sugar_g: 1.0,
    fat_g: 21.0,
    sat_fat_g: 4.2,
    sodium_mg: 720,
    protein_source: 'Q2',
    cooking: 'fried',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://www.burgerking.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 7. 슬로우캘리 & 포케올데이 (5개)
  {
    menu_id: 'fr-slowcali-classic-tuna-poke-380',
    channel: 'fr',
    brand: '슬로우캘리',
    name: '클래식 참치 포케 380g',
    category: '샐러드',
    price_krw: 11500,
    serving_g: 380,
    kcal: 540,
    protein_g: 28.0,
    carb_g: 68.0,
    sugar_g: 7.0,
    fat_g: 16.0,
    sat_fat_g: 2.8,
    sodium_mg: 780,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '신선한 생참치와 현미밥 단백질 28g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://slowcali.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-slowcali-classic-salmon-poke-380',
    channel: 'fr',
    brand: '슬로우캘리',
    name: '클래식 연어 포케 380g',
    category: '샐러드',
    price_krw: 12500,
    serving_g: 380,
    kcal: 575,
    protein_g: 26.0,
    carb_g: 66.0,
    sugar_g: 7.2,
    fat_g: 21.0,
    sat_fat_g: 3.5,
    sodium_mg: 740,
    protein_source: 'Q3',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '생연어 슈퍼푸드 보울 단백질 26g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://slowcali.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-slowcali-beef-steak-bowl-390',
    channel: 'fr',
    brand: '슬로우캘리',
    name: '부채살 스테이크 보울 390g',
    category: '샐러드',
    price_krw: 13500,
    serving_g: 390,
    kcal: 595,
    protein_g: 34.0,
    carb_g: 65.0,
    sugar_g: 6.5,
    fat_g: 21.0,
    sat_fat_g: 6.5,
    sodium_mg: 820,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '마리네이드 소부채살 단백질 34g',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://slowcali.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-pokeallday-chicken-brownrice-poke-360',
    channel: 'fr',
    brand: '포케올데이',
    name: '현미밥 닭가슴살 포케 360g',
    category: '샐러드',
    price_krw: 10900,
    serving_g: 360,
    kcal: 470,
    protein_g: 31.0,
    carb_g: 62.0,
    sugar_g: 6.0,
    fat_g: 9.5,
    sat_fat_g: 1.8,
    sodium_mg: 640,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '수비드 닭가슴살 현미밥 포케',
    barcode: null,
    source_type: 'T1',
    source_url: 'https://pokeallday.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'fr-pokeallday-duck-buckwheat-poke-350',
    channel: 'fr',
    brand: '포케올데이',
    name: '메밀면 훈제오리 포케 350g',
    category: '샐러드',
    price_krw: 11900,
    serving_g: 350,
    kcal: 510,
    protein_g: 24.0,
    carb_g: 58.0,
    sugar_g: 8.0,
    fat_g: 18.0,
    sat_fat_g: 4.5,
    sodium_mg: 720,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: null,
    source_type: 'T1',
    source_url: 'https://pokeallday.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // [2단계: 편의점 식사류 (cvs: 삼각김밥, 줄김밥, 샌드위치)] 19개
  // ─────────────────────────────────────────────────────────────
  // GS25 (8개)
  {
    menu_id: 'cvs-gs25-tuna-mayo-big-triangle-155',
    channel: 'cvs',
    brand: 'GS25',
    name: '참치마요 더큰삼각김밥 155g',
    category: '삼각김밥/주먹밥',
    price_krw: 1700,
    serving_g: 155,
    kcal: 298,
    protein_g: 8.5,
    carb_g: 46.0,
    sugar_g: 2.1,
    fat_g: 8.8,
    sat_fat_g: 1.6,
    sodium_mg: 590,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068390018',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-new-tuna-kimchi-triangle-110',
    channel: 'cvs',
    brand: 'GS25',
    name: '뉴참치김치 삼각김밥 110g',
    category: '삼각김밥/주먹밥',
    price_krw: 1200,
    serving_g: 110,
    kcal: 185,
    protein_g: 6.0,
    carb_g: 35.0,
    sugar_g: 2.5,
    fat_g: 2.1,
    sat_fat_g: 0.5,
    sodium_mg: 620,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068390025',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-direct-bulgogi-triangle-110',
    channel: 'cvs',
    brand: 'GS25',
    name: '직화불고기 삼각김밥 110g',
    category: '삼각김밥/주먹밥',
    price_krw: 1300,
    serving_g: 110,
    kcal: 195,
    protein_g: 6.5,
    carb_g: 36.0,
    sugar_g: 3.2,
    fat_g: 2.8,
    sat_fat_g: 0.9,
    sodium_mg: 540,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068390032',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-jeonju-bibim-triangle-110',
    channel: 'cvs',
    brand: 'GS25',
    name: '전주비빔 삼각김밥 110g',
    category: '삼각김밥/주먹밥',
    price_krw: 1200,
    serving_g: 110,
    kcal: 180,
    protein_g: 5.5,
    carb_g: 35.0,
    sugar_g: 3.0,
    fat_g: 2.2,
    sat_fat_g: 0.6,
    sodium_mg: 560,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068390049',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-tong-sausage-gimbap-240',
    channel: 'cvs',
    brand: 'GS25',
    name: '통소시지 김밥 240g',
    category: '도시락',
    price_krw: 3200,
    serving_g: 240,
    kcal: 430,
    protein_g: 15.0,
    carb_g: 58.0,
    sugar_g: 5.0,
    fat_g: 15.0,
    sat_fat_g: 4.8,
    sodium_mg: 980,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068390056',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-tuna-mayo-gimbap-235',
    channel: 'cvs',
    brand: 'GS25',
    name: '참치마요 김밥 235g',
    category: '도시락',
    price_krw: 3000,
    serving_g: 235,
    kcal: 395,
    protein_g: 12.0,
    carb_g: 59.0,
    sugar_g: 4.2,
    fat_g: 11.5,
    sat_fat_g: 2.1,
    sodium_mg: 890,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068390063',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-double-cheese-bulgogi-gimbap-245',
    channel: 'cvs',
    brand: 'GS25',
    name: '더블치즈 불고기 김밥 245g',
    category: '도시락',
    price_krw: 3400,
    serving_g: 245,
    kcal: 445,
    protein_g: 14.5,
    carb_g: 61.0,
    sugar_g: 6.0,
    fat_g: 14.0,
    sat_fat_g: 5.2,
    sodium_mg: 1020,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068390070',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-gs25-egg-sandwich-165',
    channel: 'cvs',
    brand: 'GS25',
    name: '듬뿍 에그 샌드위치 165g',
    category: '샌드위치/버거',
    price_krw: 2700,
    serving_g: 165,
    kcal: 360,
    protein_g: 11.5,
    carb_g: 34.0,
    sugar_g: 5.5,
    fat_g: 19.0,
    sat_fat_g: 4.5,
    sodium_mg: 620,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068390087',
    source_type: 'T2',
    source_url: 'http://gs25.gsretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // CU (7개)
  {
    menu_id: 'cvs-cu-double-topping-tuna-mayo-150',
    channel: 'cvs',
    brand: 'CU',
    name: '토핑2배 참치마요 삼각김밥 150g',
    category: '삼각김밥/주먹밥',
    price_krw: 1600,
    serving_g: 150,
    kcal: 290,
    protein_g: 8.8,
    carb_g: 44.0,
    sugar_g: 2.0,
    fat_g: 8.5,
    sat_fat_g: 1.5,
    sodium_mg: 580,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068490015',
    source_type: 'T2',
    source_url: 'https://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-spicy-pork-triangle-115',
    channel: 'cvs',
    brand: 'CU',
    name: '매콤제육 삼각김밥 115g',
    category: '삼각김밥/주먹밥',
    price_krw: 1300,
    serving_g: 115,
    kcal: 195,
    protein_g: 6.8,
    carb_g: 35.0,
    sugar_g: 3.5,
    fat_g: 2.9,
    sat_fat_g: 0.9,
    sodium_mg: 610,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068490022',
    source_type: 'T2',
    source_url: 'https://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-tong-spam-triangle-120',
    channel: 'cvs',
    brand: 'CU',
    name: '통스팸 삼각김밥 120g',
    category: '삼각김밥/주먹밥',
    price_krw: 1500,
    serving_g: 120,
    kcal: 235,
    protein_g: 7.2,
    carb_g: 34.0,
    sugar_g: 2.8,
    fat_g: 7.8,
    sat_fat_g: 2.8,
    sodium_mg: 680,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068490039',
    source_type: 'T2',
    source_url: 'https://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-dakgalbi-triangle-115',
    channel: 'cvs',
    brand: 'CU',
    name: '닭갈비 삼각김밥 115g',
    category: '삼각김밥/주먹밥',
    price_krw: 1300,
    serving_g: 115,
    kcal: 190,
    protein_g: 6.5,
    carb_g: 34.0,
    sugar_g: 3.0,
    fat_g: 2.8,
    sat_fat_g: 0.8,
    sodium_mg: 590,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068490046',
    source_type: 'T2',
    source_url: 'https://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-mukeunji-tuna-gimbap-240',
    channel: 'cvs',
    brand: 'CU',
    name: '묵은지 참치 김밥 240g',
    category: '도시락',
    price_krw: 3200,
    serving_g: 240,
    kcal: 385,
    protein_g: 13.0,
    carb_g: 58.0,
    sugar_g: 4.5,
    fat_g: 10.5,
    sat_fat_g: 2.0,
    sodium_mg: 940,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068490053',
    source_type: 'T2',
    source_url: 'https://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-handon-gimbap-245',
    channel: 'cvs',
    brand: 'CU',
    name: '한돈 듬뿍 김밥 245g',
    category: '도시락',
    price_krw: 3300,
    serving_g: 245,
    kcal: 420,
    protein_g: 14.0,
    carb_g: 60.0,
    sugar_g: 5.8,
    fat_g: 12.8,
    sat_fat_g: 4.1,
    sodium_mg: 990,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068490060',
    source_type: 'T2',
    source_url: 'https://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-cu-cajun-chicken-sandwich-180',
    channel: 'cvs',
    brand: 'CU',
    name: '케이준 치킨 샌드위치 180g',
    category: '샌드위치/버거',
    price_krw: 2900,
    serving_g: 180,
    kcal: 380,
    protein_g: 14.0,
    carb_g: 42.0,
    sugar_g: 6.2,
    fat_g: 16.5,
    sat_fat_g: 3.8,
    sodium_mg: 750,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068490077',
    source_type: 'T2',
    source_url: 'https://cu.bgfretail.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 세븐일레븐 (4개)
  {
    menu_id: 'cvs-7eleven-bigger-tuna-mayo-150',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '더커진 참치마요네즈 삼각김밥 150g',
    category: '삼각김밥/주먹밥',
    price_krw: 1600,
    serving_g: 150,
    kcal: 292,
    protein_g: 8.4,
    carb_g: 45.0,
    sugar_g: 2.2,
    fat_g: 8.4,
    sat_fat_g: 1.6,
    sodium_mg: 570,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068590012',
    source_type: 'T2',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-7eleven-jeonju-bibim-110',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '전주비빔 삼각김밥 110g',
    category: '삼각김밥/주먹밥',
    price_krw: 1200,
    serving_g: 110,
    kcal: 182,
    protein_g: 5.4,
    carb_g: 35.0,
    sugar_g: 2.8,
    fat_g: 2.3,
    sat_fat_g: 0.6,
    sodium_mg: 550,
    protein_source: 'Q2',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068590029',
    source_type: 'T2',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-7eleven-egg-rich-gimbap-220',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '계란 듬뿍 김밥 220g',
    category: '도시락',
    price_krw: 3300,
    serving_g: 220,
    kcal: 340,
    protein_g: 14.5,
    carb_g: 44.0,
    sugar_g: 4.0,
    fat_g: 11.0,
    sat_fat_g: 3.0,
    sodium_mg: 780,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '단백질 가득한 부드러운 지단 김밥',
    barcode: '8801068590036',
    source_type: 'T2',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'cvs-7eleven-ham-egg-toast-170',
    channel: 'cvs',
    brand: '세븐일레븐',
    name: '햄에그 토스트 샌드위치 170g',
    category: '샌드위치/버거',
    price_krw: 2800,
    serving_g: 170,
    kcal: 375,
    protein_g: 13.5,
    carb_g: 38.0,
    sugar_g: 6.8,
    fat_g: 18.0,
    sat_fat_g: 4.8,
    sodium_mg: 720,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801068590043',
    source_type: 'T2',
    source_url: 'https://www.7-eleven.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // [3단계: 대형마트 & 코스트코 & 수산물 mart] 15개
  // ─────────────────────────────────────────────────────────────
  // 코스트코 (6개)
  {
    menu_id: 'mart-costco-rotisserie-chicken-serving-200',
    channel: 'mart',
    brand: '코스트코',
    name: '로티세리 치킨 (1/4마리 200g 기준)',
    category: '닭가슴살/육가공',
    price_krw: 1750,
    serving_g: 200,
    kcal: 346,
    protein_g: 34.0,
    carb_g: 0.8,
    sugar_g: 0.2,
    fat_g: 22.0,
    sat_fat_g: 6.0,
    sodium_mg: 600,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '코스트코 오븐 통닭 1회 34g 고단백',
    barcode: '0096619123456',
    source_type: 'T2',
    source_url: 'https://www.costco.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-costco-kirkland-greek-yogurt-serving-100',
    channel: 'mart',
    brand: '코스트코',
    name: '커클랜드 시그니처 무지방 그릭요거트 (100g 기준)',
    category: '유제품/음료',
    price_krw: 1100,
    serving_g: 100,
    kcal: 55,
    protein_g: 10.0,
    carb_g: 3.8,
    sugar_g: 2.8,
    fat_g: 0.0,
    sat_fat_g: 0.0,
    sodium_mg: 38,
    protein_source: 'Q1',
    cooking: 'raw',
    marketing_claim: 1,
    claim_text: '무지방 무설탕 100g당 단백질 10g',
    barcode: '0096619123463',
    source_type: 'T2',
    source_url: 'https://www.costco.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-costco-suzies-grilled-chicken-100',
    channel: 'mart',
    brand: '수지스',
    name: '수지스 그릴드 닭가슴살 100g (1팩 기준)',
    category: '닭가슴살/육가공',
    price_krw: 1500,
    serving_g: 100,
    kcal: 110,
    protein_g: 23.0,
    carb_g: 1.0,
    sugar_g: 0.5,
    fat_g: 1.2,
    sat_fat_g: 0.35,
    sodium_mg: 360,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '코스트코 스테디셀러 그릴드 닭가슴살',
    barcode: '8809278912345',
    source_type: 'T2',
    source_url: 'https://www.costco.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-costco-suzies-pepper-chicken-100',
    channel: 'mart',
    brand: '수지스',
    name: '수지스 페퍼 닭가슴살 100g (1팩 기준)',
    category: '닭가슴살/육가공',
    price_krw: 1500,
    serving_g: 100,
    kcal: 112,
    protein_g: 23.5,
    carb_g: 1.2,
    sugar_g: 0.5,
    fat_g: 1.3,
    sat_fat_g: 0.38,
    sodium_mg: 370,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '굵은 통후추가 씹히는 닭가슴살',
    barcode: '8809278912352',
    source_type: 'T2',
    source_url: 'https://www.costco.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-costco-kirkland-protein-bar-cookiedough-60',
    channel: 'mart',
    brand: '코스트코',
    name: '커클랜드 시그니처 프로틴바 초콜릿칩 쿠키도우 60g',
    category: '과자/바',
    price_krw: 2200,
    serving_g: 60,
    kcal: 190,
    protein_g: 21.0,
    carb_g: 11.0,
    sugar_g: 1.0,
    fat_g: 7.0,
    sat_fat_g: 2.5,
    sodium_mg: 190,
    fiber_g: 10.0,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: 'WPI/WPC 단백질 21g 식이섬유 10g',
    barcode: '0096619123470',
    source_type: 'T2',
    source_url: 'https://www.costco.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-costco-kirkland-protein-bar-brownie-60',
    channel: 'mart',
    brand: '코스트코',
    name: '커클랜드 시그니처 프로틴바 초콜릿 브라우니 60g',
    category: '과자/바',
    price_krw: 2200,
    serving_g: 60,
    kcal: 190,
    protein_g: 21.0,
    carb_g: 11.0,
    sugar_g: 1.0,
    fat_g: 7.0,
    sat_fat_g: 2.5,
    sodium_mg: 170,
    fiber_g: 10.0,
    protein_source: 'Q1',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '단백질 21g 저당 프로틴바',
    barcode: '0096619123487',
    source_type: 'T2',
    source_url: 'https://www.costco.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // CJ제일제당 비비고 순살 생선구이 & 동원/한성 게맛살 (6개)
  {
    menu_id: 'mart-cj-bibigo-mackerel-grilled-60',
    channel: 'mart',
    brand: 'CJ제일제당',
    name: '비비고 순살 고등어구이 60g',
    category: '기타',
    price_krw: 3980,
    serving_g: 60,
    kcal: 160,
    protein_g: 14.0,
    carb_g: 0.5,
    sugar_g: 0.0,
    fat_g: 11.0,
    sat_fat_g: 2.8,
    sodium_mg: 280,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '전자레인지 1분 뼈없는 순살 고등어',
    barcode: '8801007839011',
    source_type: 'T2',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-cj-bibigo-spanish-mackerel-grilled-60',
    channel: 'mart',
    brand: 'CJ제일제당',
    name: '비비고 순살 삼치구이 60g',
    category: '기타',
    price_krw: 4280,
    serving_g: 60,
    kcal: 115,
    protein_g: 15.0,
    carb_g: 0.5,
    sugar_g: 0.0,
    fat_g: 6.0,
    sat_fat_g: 1.5,
    sodium_mg: 260,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '담백한 삼치 순살 단백질 15g',
    barcode: '8801007839028',
    source_type: 'T2',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-cj-bibigo-flounder-grilled-60',
    channel: 'mart',
    brand: 'CJ제일제당',
    name: '비비고 순살 가자미구이 60g',
    category: '기타',
    price_krw: 4280,
    serving_g: 60,
    kcal: 85,
    protein_g: 13.0,
    carb_g: 1.0,
    sugar_g: 0.0,
    fat_g: 3.0,
    sat_fat_g: 0.7,
    sodium_mg: 290,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '지방이 적고 부드러운 가자미살',
    barcode: '8801007839035',
    source_type: 'T2',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-cj-bibigo-salmon-grilled-60',
    channel: 'mart',
    brand: 'CJ제일제당',
    name: '비비고 순살 연어구이 60g',
    category: '기타',
    price_krw: 4480,
    serving_g: 60,
    kcal: 130,
    protein_g: 14.0,
    carb_g: 0.0,
    sugar_g: 0.0,
    fat_g: 8.0,
    sat_fat_g: 1.8,
    sodium_mg: 270,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '촉촉한 노르웨이산 연어 순살',
    barcode: '8801007839042',
    source_type: 'T2',
    source_url: 'https://www.cj.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-dongwon-real-crabs-144',
    channel: 'mart',
    brand: '동원',
    name: '동원 리얼 크랩스 게맛살 144g',
    category: '기타',
    price_krw: 2980,
    serving_g: 144,
    kcal: 125,
    protein_g: 12.0,
    carb_g: 18.0,
    sugar_g: 6.0,
    fat_g: 0.5,
    sat_fat_g: 0.1,
    sodium_mg: 680,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '명태 연육 100% 지방 0.5g 컷팅 간식',
    barcode: '8801047190014',
    source_type: 'T2',
    source_url: 'https://www.dongwon.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-hansung-crami-150',
    channel: 'mart',
    brand: '한성기업',
    name: '한성 크래미 150g',
    category: '기타',
    price_krw: 2980,
    serving_g: 150,
    kcal: 135,
    protein_g: 13.0,
    carb_g: 19.0,
    sugar_g: 6.5,
    fat_g: 0.6,
    sat_fat_g: 0.1,
    sodium_mg: 710,
    protein_source: 'Q3',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '부드러운 게맛살 순수 단백질',
    barcode: '8801077190011',
    source_type: 'T2',
    source_url: 'https://www.hansungfood.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 풀무원 두부면 & 롤유부초밥 (3개)
  {
    menu_id: 'mart-pulmuone-tofu-noodle-thin-100',
    channel: 'mart',
    brand: '풀무원',
    name: '풀무원 얇은 두부면 100g',
    category: '기타',
    price_krw: 2900,
    serving_g: 100,
    kcal: 160,
    protein_g: 15.0,
    carb_g: 3.0,
    sugar_g: 0.5,
    fat_g: 10.0,
    sat_fat_g: 1.6,
    sodium_mg: 15,
    protein_source: 'Q4',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '밀가루 제로 식물성 단백질 15g 두부면',
    barcode: '8801114139011',
    source_type: 'T2',
    source_url: 'https://www.pulmuone.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-pulmuone-tofu-noodle-wide-100',
    channel: 'mart',
    brand: '풀무원',
    name: '풀무원 넓은 두부면 100g',
    category: '기타',
    price_krw: 2900,
    serving_g: 100,
    kcal: 160,
    protein_g: 15.0,
    carb_g: 3.0,
    sugar_g: 0.5,
    fat_g: 10.0,
    sat_fat_g: 1.6,
    sodium_mg: 15,
    protein_source: 'Q4',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '파스타 국수 대체 고단백 두부면',
    barcode: '8801114139028',
    source_type: 'T2',
    source_url: 'https://www.pulmuone.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-pulmuone-roll-yubuchobap-140',
    channel: 'mart',
    brand: '풀무원',
    name: '풀무원 롤유부초밥 (유부 140g 기준)',
    category: '기타',
    price_krw: 4980,
    serving_g: 140,
    kcal: 260,
    protein_g: 14.0,
    carb_g: 12.0,
    sugar_g: 8.0,
    fat_g: 18.0,
    sat_fat_g: 3.2,
    sodium_mg: 620,
    protein_source: 'Q4',
    cooking: 'processed',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8801114139035',
    source_type: 'T2',
    source_url: 'https://www.pulmuone.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // ─────────────────────────────────────────────────────────────
  // [4단계: 전문 식단 플랫폼 HMR online] 16개
  // ─────────────────────────────────────────────────────────────
  // 미트리 (5개)
  {
    menu_id: 'online-metree-chicken-fried-rice-garlic-200',
    channel: 'online',
    brand: '미트리',
    name: '미트리 닭가슴살 볶음밥 갈릭 200g',
    category: '도시락',
    price_krw: 2600,
    serving_g: 200,
    kcal: 360,
    protein_g: 30.0,
    carb_g: 48.0,
    sugar_g: 2.0,
    fat_g: 5.0,
    sat_fat_g: 1.2,
    sodium_mg: 520,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '국내산 닭가슴살 단백질 30g 볶음밥',
    barcode: '8809654190011',
    source_type: 'T2',
    source_url: 'https://metree.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-metree-chicken-fried-rice-kimchi-200',
    channel: 'online',
    brand: '미트리',
    name: '미트리 닭가슴살 볶음밥 김치 200g',
    category: '도시락',
    price_krw: 2600,
    serving_g: 200,
    kcal: 345,
    protein_g: 29.0,
    carb_g: 47.0,
    sugar_g: 3.0,
    fat_g: 4.8,
    sat_fat_g: 1.1,
    sodium_mg: 640,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '매콤 아삭 김치 닭가슴살 단백질 29g',
    barcode: '8809654190028',
    source_type: 'T2',
    source_url: 'https://metree.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-metree-chicken-fried-rice-bulgogi-200',
    channel: 'online',
    brand: '미트리',
    name: '미트리 닭가슴살 볶음밥 소불고기맛 200g',
    category: '도시락',
    price_krw: 2600,
    serving_g: 200,
    kcal: 365,
    protein_g: 28.0,
    carb_g: 50.0,
    sugar_g: 4.0,
    fat_g: 5.2,
    sat_fat_g: 1.3,
    sodium_mg: 580,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '달콤 짭짤 소불고기맛 단백질 28g',
    barcode: '8809654190035',
    source_type: 'T2',
    source_url: 'https://metree.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-metree-beef-ball-original-100',
    channel: 'online',
    brand: '미트리',
    name: '미트리 소고기 볼 오리지널 100g',
    category: '닭가슴살/육가공',
    price_krw: 2400,
    serving_g: 100,
    kcal: 155,
    protein_g: 20.0,
    carb_g: 4.0,
    sugar_g: 1.5,
    fat_g: 6.5,
    sat_fat_g: 2.8,
    sodium_mg: 340,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '부드러운 홍두깨살 소고기볼 단백질 20g',
    barcode: '8809654190042',
    source_type: 'T2',
    source_url: 'https://metree.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-metree-steam-chicken-chili-100',
    channel: 'online',
    brand: '미트리',
    name: '미트리 스팀 닭가슴살 칠리맛 100g',
    category: '닭가슴살/육가공',
    price_krw: 1900,
    serving_g: 100,
    kcal: 130,
    protein_g: 24.0,
    carb_g: 4.5,
    sugar_g: 3.0,
    fat_g: 1.8,
    sat_fat_g: 0.5,
    sodium_mg: 380,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '촉촉한 스팀 공법 단백질 24g',
    barcode: '8809654190059',
    source_type: 'T2',
    source_url: 'https://metree.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 맛있닭 (4개)
  {
    menu_id: 'online-masitdak-dumpling-kimchi-168',
    channel: 'online',
    brand: '맛있닭',
    name: '맛있닭 닭가슴살 한끼 만두 김치맛 168g',
    category: '기타',
    price_krw: 3200,
    serving_g: 168,
    kcal: 290,
    protein_g: 26.0,
    carb_g: 36.0,
    sugar_g: 3.5,
    fat_g: 4.5,
    sat_fat_g: 1.2,
    sodium_mg: 640,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '쫄깃한 타피오카 피 단백질 26g 만두',
    barcode: '8809543190011',
    source_type: 'T2',
    source_url: 'https://www.rankingdak.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-masitdak-dumpling-galbi-168',
    channel: 'online',
    brand: '맛있닭',
    name: '맛있닭 닭가슴살 한끼 만두 갈비맛 168g',
    category: '기타',
    price_krw: 3200,
    serving_g: 168,
    kcal: 305,
    protein_g: 26.0,
    carb_g: 38.0,
    sugar_g: 5.0,
    fat_g: 5.0,
    sat_fat_g: 1.4,
    sodium_mg: 590,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '달콤한 갈비맛 소 단백질 26g',
    barcode: '8809543190028',
    source_type: 'T2',
    source_url: 'https://www.rankingdak.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-masitdak-chicken-burrito-chili-180',
    channel: 'online',
    brand: '맛있닭',
    name: '맛있닭 닭가슴살 한끼 브리또 칠리 180g',
    category: '샌드위치/버거',
    price_krw: 3400,
    serving_g: 180,
    kcal: 340,
    protein_g: 22.0,
    carb_g: 41.0,
    sugar_g: 4.0,
    fat_g: 9.8,
    sat_fat_g: 3.5,
    sodium_mg: 620,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '또띠아 속 닭가슴살과 통모짜렐라 치즈 단백질 22g',
    barcode: '8809543190035',
    source_type: 'T2',
    source_url: 'https://www.rankingdak.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-masitdak-chicken-sausage-smoked-100',
    channel: 'online',
    brand: '맛있닭',
    name: '맛있닭 닭가슴살 소시지 훈제맛 100g',
    category: '닭가슴살/육가공',
    price_krw: 1900,
    serving_g: 100,
    kcal: 145,
    protein_g: 21.0,
    carb_g: 3.0,
    sugar_g: 1.0,
    fat_g: 5.5,
    sat_fat_g: 1.5,
    sodium_mg: 390,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '탱글탱글 훈제 소시지 단백질 21g',
    barcode: '8809543190042',
    source_type: 'T2',
    source_url: 'https://www.rankingdak.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 바디나인 & 굽네몰 (3개)
  {
    menu_id: 'online-bodynine-spicy-chicken-150',
    channel: 'online',
    brand: '바디나인',
    name: '바디나인 내가 몸짱이 될 닭 스파이시 150g',
    category: '닭가슴살/육가공',
    price_krw: 2900,
    serving_g: 150,
    kcal: 185,
    protein_g: 32.0,
    carb_g: 4.0,
    sugar_g: 2.5,
    fat_g: 4.2,
    sat_fat_g: 1.1,
    sodium_mg: 460,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '150g 대용량 단백질 32g 닭가슴살',
    barcode: '8809632190011',
    source_type: 'T2',
    source_url: 'https://bodynine.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-goobne-road-dak-subeed-100',
    channel: 'online',
    brand: '굽네몰',
    name: '굽네몰 로드닭 저염 수비드 닭가슴살 100g',
    category: '닭가슴살/육가공',
    price_krw: 2200,
    serving_g: 100,
    kcal: 115,
    protein_g: 26.0,
    carb_g: 0.5,
    sugar_g: 0.0,
    fat_g: 1.2,
    sat_fat_g: 0.4,
    sodium_mg: 45,
    protein_source: 'Q1',
    cooking: 'cooked',
    marketing_claim: 1,
    claim_text: '나트륨 45mg 초저염 수비드 단백질 26g',
    barcode: '8809421190011',
    source_type: 'T2',
    source_url: 'https://www.goobnemall.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-goobne-somatdak-chicken-thigh-100',
    channel: 'online',
    brand: '굽네몰',
    name: '굽네몰 소맛닭 통다리살 구이 100g',
    category: '닭가슴살/육가공',
    price_krw: 2900,
    serving_g: 100,
    kcal: 155,
    protein_g: 20.0,
    carb_g: 3.0,
    sugar_g: 2.0,
    fat_g: 7.0,
    sat_fat_g: 2.0,
    sodium_mg: 390,
    protein_source: 'Q2',
    cooking: 'cooked',
    marketing_claim: 0,
    claim_text: null,
    barcode: '8809421190028',
    source_type: 'T2',
    source_url: 'https://www.goobnemall.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },

  // 그릭데이, 요즘, 매일두유 (4개)
  {
    menu_id: 'online-greekday-signature-plain-100',
    channel: 'online',
    brand: '그릭데이',
    name: '그릭데이 시그니처 그릭요거트 100g',
    category: '유제품/음료',
    price_krw: 3800,
    serving_g: 100,
    kcal: 160,
    protein_g: 11.4,
    carb_g: 4.2,
    sugar_g: 1.8,
    fat_g: 10.8,
    sat_fat_g: 7.2,
    sodium_mg: 35,
    protein_source: 'Q1',
    cooking: 'raw',
    marketing_claim: 1,
    claim_text: '원유 99.9% 초꾸덕 시그니처 그릭요거트',
    barcode: '8809581190011',
    source_type: 'T2',
    source_url: 'https://greekday.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-greekday-light-greek-yogurt-100',
    channel: 'online',
    brand: '그릭데이',
    name: '그릭데이 라이트 그릭요거트 100g',
    category: '유제품/음료',
    price_krw: 3800,
    serving_g: 100,
    kcal: 100,
    protein_g: 10.5,
    carb_g: 5.0,
    sugar_g: 2.0,
    fat_g: 4.2,
    sat_fat_g: 2.8,
    sodium_mg: 40,
    protein_source: 'Q1',
    cooking: 'raw',
    marketing_claim: 1,
    claim_text: '지방 낮춘 산뜻한 라이트 그릭요거트',
    barcode: '8809581190028',
    source_type: 'T2',
    source_url: 'https://greekday.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'online-yozm-plain-greek-yogurt-100',
    channel: 'online',
    brand: '요즘',
    name: '요즘 플레인 그릭요거트 100g',
    category: '유제품/음료',
    price_krw: 4300,
    serving_g: 100,
    kcal: 175,
    protein_g: 11.0,
    carb_g: 4.8,
    sugar_g: 2.1,
    fat_g: 12.0,
    sat_fat_g: 8.0,
    sodium_mg: 42,
    protein_source: 'Q1',
    cooking: 'raw',
    marketing_claim: 1,
    claim_text: '정통 그리스 유청 분리 방식 플레인',
    barcode: '8809623190011',
    source_type: 'T2',
    source_url: 'https://yozm.co.kr',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  },
  {
    menu_id: 'mart-maeil-soymilk-high-protein-190',
    channel: 'mart',
    brand: '매일유업',
    name: '매일두유 고단백 190mL',
    category: '유제품/음료',
    price_krw: 1200,
    serving_g: 190,
    kcal: 110,
    protein_g: 12.0,
    carb_g: 4.5,
    sugar_g: 1.2,
    fat_g: 5.0,
    sat_fat_g: 0.8,
    sodium_mg: 160,
    protein_source: 'Q4',
    cooking: 'processed',
    marketing_claim: 1,
    claim_text: '설탕 무첨가 콩 단백질 12g 고단백 두유',
    barcode: '8801121190011',
    source_type: 'T2',
    source_url: 'https://www.maeil.com',
    verified_at: '2026-09-15',
    rule_version: 'v1.0'
  }
];

function main() {
  const seedPath = path.join(rootDir, 'data', 'seed.json');
  const existingSeed = JSON.parse(fs.readFileSync(seedPath, 'utf-8'));
  const existingIdSet = new Set(existingSeed.map(x => x.menu_id));

  console.log(`기존 DB 품목 수: ${existingSeed.length}개`);
  console.log(`신규 추가 대상: ${newProducts.length}개`);

  // QA 검증
  let failCount = 0;
  let warnCount = 0;
  for (const item of newProducts) {
    const qa = validateMenuQA(item, existingIdSet);
    if (!qa.valid) {
      console.error(`❌ [QA 에러] ${item.name}:`, qa.errors);
      failCount++;
    }
    if (qa.warnings.length > 0) {
      console.warn(`⚠️ [QA 경고] ${item.name}:`, qa.warnings);
      warnCount++;
    }
    existingIdSet.add(item.menu_id);
  }

  if (failCount > 0) {
    console.error(`💥 QA 에러 ${failCount}건 발생으로 중단합니다.`);
    process.exit(1);
  }

  console.log(`✅ 신규 ${newProducts.length}개 품목 R1~R5 QA 통과 완료 (경고: ${warnCount}건)`);

  // 병합
  const merged = [...existingSeed, ...newProducts];
  fs.writeFileSync(seedPath, JSON.stringify(merged, null, 2), 'utf-8');
  console.log(`💾 data/seed.json 업데이트 완료! (총 ${merged.length}개)`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
